- src/main/java/com/teamddd/duckmap/DuckmapApplication.java
- src/main/java/com/teamddd/duckmap/entity/Artist.java
- src/main/java/com/teamddd/duckmap/entity/ArtistType.java
- src/main/java/com/teamddd/duckmap/entity/Event.java
- src/main/java/com/teamddd/duckmap/entity/EventArtist.java
- src/main/java/com/teamddd/duckmap/entity/EventBookmark.java
- src/main/java/com/teamddd/duckmap/entity/EventBookmarkFolder.java
- src/main/java/com/teamddd/duckmap/entity/EventCategory.java
- src/main/java/com/teamddd/duckmap/entity/EventImage.java
- src/main/java/com/teamddd/duckmap/entity/EventInfoCategory.java
- src/main/java/com/teamddd/duckmap/entity/EventLike.java
- src/main/java/com/teamddd/duckmap/entity/LastSearchArtist.java
- src/main/java/com/teamddd/duckmap/entity/Review.java
- src/main/java/com/teamddd/duckmap/entity/ReviewImage.java
- src/main/java/com/teamddd/duckmap/entity/User.java
Entity를 생성
확인 요청 사항:
1. 기존 엔티티
EventInfo: 이벤트 
EventInfoCategory: 이벤트에 지정한 카테고리
EventCategory : 카테고리
변경 후(엔티티는 이렇게 적용, DB테이블 수정도 고려)
Event: 이벤트 
EventCategory: 이벤트에 지정한 카테고리
Category: 카테고리
2. Bookmark-BookmarkFolder의 연관관계가 애매하여 일단은 N:1 단방향으로 매핑했습니다.
3. EventImage의 isMain을 isThumbnail로 이름 변경 어떨까요?
> Feat: Entity 생성

- src/main/java/com/teamddd/duckmap/entity/Artist.java
- src/main/java/com/teamddd/duckmap/entity/ArtistType.java
- src/main/java/com/teamddd/duckmap/entity/Event.java
- src/main/java/com/teamddd/duckmap/entity/EventArtist.java
- src/main/java/com/teamddd/duckmap/entity/EventBookmark.java
- src/main/java/com/teamddd/duckmap/entity/EventBookmarkFolder.java
- src/main/java/com/teamddd/duckmap/entity/EventCategory.java
- src/main/java/com/teamddd/duckmap/entity/EventImage.java
- src/main/java/com/teamddd/duckmap/entity/EventInfoCategory.java
- src/main/java/com/teamddd/duckmap/entity/EventLike.java
- src/main/java/com/teamddd/duckmap/entity/LastSearchArtist.java
- src/main/java/com/teamddd/duckmap/entity/Review.java
- src/main/java/com/teamddd/duckmap/entity/ReviewImage.java
- src/main/java/com/teamddd/duckmap/entity/User.java
> Style: Entity 재정렬

- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/dto/CreateEventReq.java
- src/main/java/com/teamddd/duckmap/dto/CreateEventRes.java
- src/main/java/com/teamddd/duckmap/dto/EventRes.java
- src/main/java/com/teamddd/duckmap/dto/ImageRes.java
- src/main/java/com/teamddd/duckmap/dto/MockArtistRes.java
- src/main/java/com/teamddd/duckmap/dto/MockCategoryRes.java
- src/main/java/com/teamddd/duckmap/dto/Result.java
- src/main/java/com/teamddd/duckmap/dto/UpdateEventReq.java
- src/main/java/com/teamddd/duckmap/dto/UpdateEventRes.java
> 이벤트 crud mock api 생성
> EventController
- POST /events
- GET /events/{id}
- EventRes에서 ArtistRes, CategoryRes가 아직 없어서 일단 mock으로 대체했습니다. 만드시면 변경할게요.
- ImageRes의 apiUrl은 properties값으로 관리할 예정입니다
- PUT /events/{id}
- DELETE /events/{id}
> Event CRUD Mock api 생성

- src/main/java/com/teamddd/duckmap/entity/Event.java
기존 타입: LocalDateTime
수정 후 타입: LocalDate
> Fix: Event 엔티티 fromDate, toDate 타입 수정

- src/main/java/com/teamddd/duckmap/DuckmapApplication.java
- src/main/java/com/teamddd/duckmap/entity/Artist.java
- src/main/java/com/teamddd/duckmap/entity/ArtistType.java
- src/main/java/com/teamddd/duckmap/entity/BaseByEntity.java
- src/main/java/com/teamddd/duckmap/entity/BaseTimeEntity.java
- src/main/java/com/teamddd/duckmap/entity/Event.java
- src/main/java/com/teamddd/duckmap/entity/EventArtist.java
- src/main/java/com/teamddd/duckmap/entity/EventBookmark.java
- src/main/java/com/teamddd/duckmap/entity/EventBookmarkFolder.java
- src/main/java/com/teamddd/duckmap/entity/EventCategory.java
- src/main/java/com/teamddd/duckmap/entity/EventImage.java
- src/main/java/com/teamddd/duckmap/entity/EventInfoCategory.java
- src/main/java/com/teamddd/duckmap/entity/EventLike.java
- src/main/java/com/teamddd/duckmap/entity/LastSearchArtist.java
- src/main/java/com/teamddd/duckmap/entity/Review.java
- src/main/java/com/teamddd/duckmap/entity/ReviewImage.java
- src/main/java/com/teamddd/duckmap/entity/User.java
BaseEntity 적용
- BaseTimeEntity 생성
- BaseByEntity 생성 (BaseTimeEntity 상속받음)
- Artist, EventCategory에 BaseByEntity 적용
-  Artist, EventCategory외에 BaseTimeEntity 적용
- @EnableJpaAuditing 적용
- AuditorAware 빈은 나중에 config 따로 만들어서 적용
> Refactor: BaseEntity 적용

- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/dto/MyEventsRes.java
> 로그인한 회원이 생성한 이벤트 목록 조회 API
- GET /events/myevent api를 EventController에 생성
- response DTO MyEventsRes list 반환
> my 이벤트 목록 조회 api 생성

- build.gradle
- src/main/java/com/teamddd/duckmap/controller/ReviewController.java
- src/main/java/com/teamddd/duckmap/dto/CreateReviewReq.java
- src/main/java/com/teamddd/duckmap/dto/CreateReviewRes.java
- src/main/java/com/teamddd/duckmap/dto/ReviewRes.java
> Review 등록 api 생성
- ReviewController POST /reviews
- CreateReviewReq, CreateReviewRes 생성
- 이미지는 1개 이상만 입력 가능
> Feat: #4 - 리뷰 등록 api 생성

- src/main/java/com/teamddd/duckmap/controller/AuthController.java
- src/main/java/com/teamddd/duckmap/dto/LoginUserReq.java
- src/main/java/com/teamddd/duckmap/dto/LoginUserRes.java
> 로그인,로그아웃 Mock api 생성
-AuthController
-POST /auth/login
-DELETE /auth/logout
- LoginUserReq
- LoginUserRes
- LoginUserReq에 email,password면 될까요?
> 로그인,로그아웃 Mock api 생성

- src/main/java/com/teamddd/duckmap/controller/ReviewController.java
- src/main/java/com/teamddd/duckmap/dto/ReviewRes.java
- src/main/java/com/teamddd/duckmap/dto/UpdateReviewReq.java
> Review update, delete mock api 생성
- ReviewController
- PUT /reviews/{id}
- DELETE /reviews/{id}
- UpdateReviewReq 생성
- ReviewRes에 createAt 추가
> Reivew UD Mock api 생성

- src/main/java/com/teamddd/duckmap/entity/Artist.java
> Artist Entity 변수명 수정
- username -> name으로 수정
> Artist Entity 변수명 수정

- src/main/java/com/teamddd/duckmap/controller/ArtistController.java
- src/main/java/com/teamddd/duckmap/controller/ArtistTypeController.java
- src/main/java/com/teamddd/duckmap/dto/ArtistRes.java
- src/main/java/com/teamddd/duckmap/dto/ArtistSearchParam.java
- src/main/java/com/teamddd/duckmap/dto/ArtistTypeRes.java
- src/main/java/com/teamddd/duckmap/dto/CreateArtistReq.java
- src/main/java/com/teamddd/duckmap/dto/CreateArtistRes.java
- src/main/java/com/teamddd/duckmap/dto/CreateArtistTypeReq.java
- src/main/java/com/teamddd/duckmap/dto/CreateArtistTypeRes.java
- src/main/java/com/teamddd/duckmap/dto/UpdateArtistReq.java
- src/main/java/com/teamddd/duckmap/dto/UpdateArtistTypeReq.java
> ArtistType CRUD Mock api 생성
- ArtistTypeController 
- POST /artists/types
- GET /artists/types
- PUT /artist/types/{id}
- DELETE /artists/types/{id}
- CreateArtistTypeRes, CreateArtistTypeReq, UpdateArtistTypeReq, ArtistTypeRes 생성
- swagger로 mock api Test 필수 진행 후 커밋
> 아티스트, 아티스트 구분 CRUD api 생성

- .gitignore
- build.gradle
> build.gradle, gitignore 수정
- build.gradle에 h2 dependency 추가
- gitignore에 application-local.yml 추가
> build.gradle, gitignore 수정

- src/main/java/com/teamddd/duckmap/controller/EventController.java
> getEvent EventRes build에서 createAt 오타 createdAt으로 수정
- EventController GET /events/{id}
> Fix: getEvent EventRes createdAt 오타 수정

- .github/PULL_REQUEST_TEMPLATE.md
> PR 템플릿 오타 수정
- Chages -> Changes
> PR 템플릿 오타 수정

- src/main/java/com/teamddd/duckmap/controller/EventCategoryController.java
- src/main/java/com/teamddd/duckmap/dto/event/category/CreateEventCategoryReq.java
- src/main/java/com/teamddd/duckmap/dto/event/category/CreateEventCategoryRes.java
- src/main/java/com/teamddd/duckmap/dto/event/category/EventCategoryRes.java
- src/main/java/com/teamddd/duckmap/dto/event/category/UpdateEventCategoryReq.java
> event category CRUD mock api 생성
- POST /events/categories
- GET /events/categories
- PUT /events/categories/{id}
- DELETE /events/categories/{id}
dto/event/category에 request, response dto 생성했습니다
좋아요, 북마크도 dto/event에 넣으면 어떠세요??
> Event Category CRUD Mock api 생성

- src/main/java/com/teamddd/duckmap/controller/ArtistController.java
- src/main/java/com/teamddd/duckmap/controller/ArtistTypeController.java
- src/main/java/com/teamddd/duckmap/dto/ArtistRes.java
- src/main/java/com/teamddd/duckmap/dto/artist/ArtistRes.java
- src/main/java/com/teamddd/duckmap/dto/artist/ArtistSearchParam.java
- src/main/java/com/teamddd/duckmap/dto/artist/ArtistTypeRes.java
- src/main/java/com/teamddd/duckmap/dto/artist/CreateArtistReq.java
- src/main/java/com/teamddd/duckmap/dto/artist/CreateArtistRes.java
- src/main/java/com/teamddd/duckmap/dto/artist/CreateArtistTypeReq.java
- src/main/java/com/teamddd/duckmap/dto/artist/CreateArtistTypeRes.java
- src/main/java/com/teamddd/duckmap/dto/artist/UpdateArtistReq.java
- src/main/java/com/teamddd/duckmap/dto/artist/UpdateArtistTypeReq.java
> ArtistRes에 groupName 추가
- ArtistRes에 groupName 추가
- ArtistController 조회 api 수정
> ArtistRes에 groupName 추가

- src/main/java/com/teamddd/duckmap/controller/LikeController.java
- src/main/java/com/teamddd/duckmap/dto/event/like/LikeRes.java
- src/main/java/com/teamddd/duckmap/dto/event/likes/LikeRes.java
> dto.event.like로 좋아요 관련 dto 이동
- dto.event.like.LikeRes
> dto.event.like로 좋아요 관련 dto 이동

- src/main/java/com/teamddd/duckmap/controller/BookmarkController.java
- src/main/java/com/teamddd/duckmap/controller/BookmarkFolderController.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkFolderRes.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkedEventRes.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/CreateBookmarkFolderReq.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/CreateBookmarkFolderRes.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/CreateBookmarkReq.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/CreateBookmarkRes.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/UpdateBookmarkFolderReq.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/UpdateBookmarkReq.java
>dto.event.bookmark로 북마크 관련 dto 이동, 변수명 변경
- dto.event.bookmark
- updateBookmark api에서 UpdateBookmarkReq -> updateBookmarkReq 변수명 변경
> dto.event.bookmark로 북마크 관련 dto 이동

- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/dto/MockArtistRes.java
- src/main/java/com/teamddd/duckmap/dto/MockCategoryRes.java
- src/main/java/com/teamddd/duckmap/dto/event/event/CreateEventReq.java
- src/main/java/com/teamddd/duckmap/dto/event/event/CreateEventRes.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventRes.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventsRes.java
- src/main/java/com/teamddd/duckmap/dto/event/event/MyEventsRes.java
- src/main/java/com/teamddd/duckmap/dto/event/event/UpdateEventReq.java
> event dto 변경
- dto/event/event로 이동
- MockRes 정식 response로 변경
- MyEventsRes 클래스명 EventsRes로 변경
- GET /events/myevent swagger summary 변경
> event dto 변경

- src/main/java/com/teamddd/duckmap/dto/review/CreateReviewReq.java
- src/main/java/com/teamddd/duckmap/dto/review/UpdateReviewReq.java
> hibernate는 swagger에서 안보여서 org.hibernate.validator.constraints.Range 에서 javax.validation.constraints.Min, Max 로 변경
- CreateReviewReq, UpdateReviewReq의 score
> Refactor: score 범위 validation 라이브러리 변경

- src/main/java/com/teamddd/duckmap/controller/ImageController.java
> 파일 content type이 image로 시작하는지 확인
- ImageController POST /images
> Feat: 이미지 저장시 이미지인지 확인

- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventsRes.java
> 이벤트 목록에서 좋아요, 북마크 표시가 보이게 하기 위해 반환값 추가
- EventsRes에 boolean like, bookmark 추가
> Feat: 이벤트 목록 조회 시 좋아요, 북마크 여부 반환 추가

- src/main/java/com/teamddd/duckmap/dto/user/CreateUserReq.java
- src/main/java/com/teamddd/duckmap/dto/user/UpdatePasswordReq.java
- src/main/java/com/teamddd/duckmap/dto/user/UpdateUserReq.java
> CreateUserReq,UpdateUserReq에 닉네임, 패스워드 정규식 추가
- CreateUserReq, UpdateUserReq
- 닉네임은 특수문자를 제외한 2~10자리
- 비밀번호는 영문 대소문자, 숫자, 특수문자를 사용한 8~16자리
> 닉네임, 패스워드 정규식 추가

- src/main/java/com/teamddd/duckmap/controller/UserController.java
- src/main/java/com/teamddd/duckmap/dto/user/CreateUserReq.java
- src/main/java/com/teamddd/duckmap/dto/user/UserRes.java
> User 생성시 userType 추가
- UserRes
- CreateUserReq
- UserController
- default 값은 USER
- UserRes, CreateUserReq에 userType 변수 enum으로 선언
> User 생성시 userType 추가

- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventRes.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventsRes.java
> event 조회시 진행중 여부 반환 추가
- EventRes, EventsRes dto에 boolean inProgress 추가
Closes: #53
> Feat: event 조회시 진행중 여부 반환 추가

- src/main/java/com/teamddd/duckmap/repository/ArtistTypeRepository.java
> artist type repository 생성
- ArtistTypeRepository 생성
> Feat: #49 - artist type repository 생성

- src/main/java/com/teamddd/duckmap/repository/ArtistRepository.java
> artist repository 생성
- ArtistRepository 생성
> Feat: #50 - artist repository 생성

- src/main/java/com/teamddd/duckmap/repository/EventCategoryRepository.java
> event category repository 생성
- EventCategoryRepository 생성
> Feat: #64 - event category repository 생성

- src/main/java/com/teamddd/duckmap/repository/EventRepository.java
> Feat: #60 - event repository 생성

- src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepository.java
- src/main/java/com/teamddd/duckmap/repository/BookmarkRepository.java
> BookmarkFolderRepository 생성
- BookmarkFolderRepository 
커밋 메시지 이름이 잘못되어서 수정했습니다.
> Feat: #77 - BookmarkFolderRepository 생성

- src/main/java/com/teamddd/duckmap/repository/ReviewRepository.java
> ReviewRepository 생성
- ReviewRepository
> Feat: #76 - ReviewRepository 생성

- src/main/java/com/teamddd/duckmap/repository/EventLikeRepository.java
> EventLikeRepository 생성
-EventLikeRepository
LikeRepository보다 명확한 이름인 EventLikeRepository로 변경
> Feat: #75 - EventLikeRepository 생성

- src/main/java/com/teamddd/duckmap/controller/AuthController.java
- src/main/java/com/teamddd/duckmap/dto/user/auth/LoginUserRes.java
> 로그인시 마지막 검색 아티스트 반환 추가
- login
- LoginUserRes
> Refactor: #80 - 로그인시 마지막 검색 아티스트 반환 추가

- build.gradle
> gradle에 querydsl 적용
- build.gradle
> Feat: gradle에 querydsl 적용

- src/main/resources/application.yml
> batch fetch size 설정으로 컬렉션 지연로딩 최적화
- application.yml
> Feat: batch fetch size 설정

- src/main/java/com/teamddd/duckmap/entity/Event.java
> Event 엔티티 eventArtists, eventInfoCategories, eventImages에 cascade = CascadeType.ALL, orphanRemoval = true 적용해서 생명주기를 Event엔티티에 의존적이게 구현
- entity/Event
> Feat: #68 - Event 엔티티 @OneToMany에 영속성전이 적용

- src/main/java/com/teamddd/duckmap/repository/UserRepository.java
>UserRepository 생성
- UserRepository
> Feat: #66 - UserRepository 생성

- src/main/java/com/teamddd/duckmap/dto/event/event/EventLikeBookmarkDto.java
- src/main/java/com/teamddd/duckmap/repository/EventRepository.java
- src/main/java/com/teamddd/duckmap/repository/EventRepositoryCustom.java
- src/main/java/com/teamddd/duckmap/repository/EventRepositoryImpl.java
- src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
> user fk로 event 목록 조회로 /myevents 반환값 조회
> Feat: #61 - user fk로 event 목록 조회 구현

- src/main/java/com/teamddd/duckmap/repository/EventRepositoryCustom.java
- src/main/java/com/teamddd/duckmap/repository/EventRepositoryImpl.java
- src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
> artist fk, 날짜기준 진행중인 event 목록 조회 구현
> Feat: #62 - artist fk, 날짜기준 진행중인 event 목록 조회 구현

- src/main/java/com/teamddd/duckmap/repository/EventRepository.java
- src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
> 날짜기준 진행중인 event hashtag 목록 조회 구현
Closes: #63
> Feat: #63 - 날짜기준 진행중인 event hashtag 목록 조회 구현

- src/main/java/com/teamddd/duckmap/repository/EventRepositoryCustom.java
- src/main/java/com/teamddd/duckmap/repository/EventRepositoryImpl.java
- src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
> event pk로 조회시 user fk로 EventLike, EventBookmark join 조회 구현
> Feat: #99 - event pk로 조회시 user fk로 EventLike, EventBookmark join 조회 구현

- src/main/java/com/teamddd/duckmap/repository/EventRepositoryImpl.java
> Refactor: #61 - event.user 불필요한 join  제거

- src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
> @DisplayName, method명 기능에 맞게 수정
- EventRepositoryTest
> Test: #63 - @DisplayName, method명 기능에 맞게 수정

- src/main/java/com/teamddd/duckmap/repository/ArtistRepository.java
- src/main/java/com/teamddd/duckmap/repository/ArtistRepositoryCustom.java
- src/main/java/com/teamddd/duckmap/repository/ArtistRepositoryImpl.java
- src/test/java/com/teamddd/duckmap/repository/ArtistRepositoryTest.java
Close: #81
> ArtistType, artistName, group의 name으로 Aritst 목록 조회 구현
- ArtistRepository
> Feat: #81 - ArtistType, artistName으로 Aritst 목록 조회 구현

- src/main/java/com/teamddd/duckmap/repository/LastSearchArtistRepository.java
> LastSearchArtistRepository 생성
- LastSearchArtistRepository
> Feat: #70 - LastSearchArtistRepository 생성

- src/test/java/com/teamddd/duckmap/repository/ArtistRepositoryTest.java
> type으로 검색 assert에 type 확인 추가
- AritstRepositoryTest
> Test: type으로 검색 assert에 type 확인 추가

- src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryCustom.java
- src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryImpl.java
- src/test/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryTest.java
> 로그인한 회원의 북마크 폴더 목록 조회
- findBookmarkFoldersByUserId 테스트 코드 작성
- findBookmarkFoldersByUserId
- 쿼리에 distinct, countDistinct 적용
> Feat: #108 - 로그인한 회원의 북마크 폴더 목록 조회

- src/main/java/com/teamddd/duckmap/entity/EventBookmarkFolder.java
> EventBookmarkFolder에 User fk 추가로 user가 빈폴더를 생성 가능하게 구현
- entity/EventBookmarkFolder
> Feat: EventBookmarkFolder에 User fk 추가

- src/main/java/com/teamddd/duckmap/controller/EventController.java
> 로그인한 user가 좋아요한 이벤트 목록 조회 api 생성
> Feat: 나의 좋아요 이벤트 목록 조회 api 생성

- src/main/java/com/teamddd/duckmap/controller/BookmarkFolderController.java
> 북마크 폴더 pk로 조회 mock api 생성
- getBookmarkFolder 추가
> Feat: 북마크 폴더 pk로 조회 mock api 생성

- src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryCustom.java
- src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryImpl.java
- src/test/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryTest.java
> userId로 북마크 폴더 목록 조회 쿼리, 테스트코드 수정
- DB 및 Entity 변경에 따른 쿼리, 테스트코드 수정
- BookmarkFolderRepositoryTest
- findBookmarkFoldersByUserId 테스트코드  수정
- BookmarkFolderRepositoryImpl
- findBookmarkFoldersByUserId 쿼리 수정
- BookmarkFolderRepositoryCustom, BookmarkFolderRepositoryImpl, BookmarkFolderRepositoryTest 누락된 코드 컨벤션 적용
> Refactor: userId로 북마크 폴더 목록 조회 쿼리, 테스트코드 수정

- src/main/java/com/teamddd/duckmap/repository/EventRepositoryCustom.java
- src/main/java/com/teamddd/duckmap/repository/EventRepositoryImpl.java
- src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
> user pk가 좋아요 한 event 목록 조회 구현
> Feat: #111 - user pk가 좋아요 한 event 목록 조회 구현

- src/main/java/com/teamddd/duckmap/repository/ArtistRepository.java
- src/test/java/com/teamddd/duckmap/repository/ArtistRepositoryTest.java
> Artist group fk로 소속 Artist 목록 조회
- ArtistRepository
> Feat: #118 - Artist group fk로 소속 Artist 목록 조회

- src/main/java/com/teamddd/duckmap/repository/EventLikeRepository.java
- src/test/java/com/teamddd/duckmap/repository/EventLikeRepositoryTest.java
>  이벤트 당 좋아요 갯수 조회
- EventLikeRepository
- countByEventId: 메서드 이름으로 쿼리 생성, eventId로 좋아요 갯수 count
- Integer로 반환
- EventLikeRepositoryTest
> Feat: #105 - 이벤트 당 좋아요 갯수 조회

- src/main/java/com/teamddd/duckmap/repository/EventLikeRepository.java
- src/test/java/com/teamddd/duckmap/repository/EventLikeRepositoryTest.java
> 반환 타입 변경
- Integer -> Long
- 공식문서의 반환타입을 따름
> Refactor: #105 - 반환 타입 변경

- src/main/java/com/teamddd/duckmap/repository/UserRepository.java
- src/test/java/com/teamddd/duckmap/repository/UserRepositoryTest.java
> email로 user 검색
- UserRepository
- UserRepositoryTest
> Feat: #112 - email로 user 검색

- src/main/java/com/teamddd/duckmap/repository/UserRepository.java
- src/test/java/com/teamddd/duckmap/repository/UserRepositoryTest.java
>username으로 user 검색
- UserRepository
- UserRepositoryTest
> Feat: #113 - username으로 user 검색

- src/main/java/com/teamddd/duckmap/repository/ReviewRepository.java
- src/test/java/com/teamddd/duckmap/repository/ReviewRepositoryTest.java
>  userId로 my Review 조회
- ReviewRepository
- ReviewRepositoryTest
-
> Feat: #88 - userId로 my Review 조회

- .gitignore
- Dockerfile
- build.gradle
- src/main/resources/application.yml
> 배포용 설정
- Dockerfile
- gradle mysql 추가
- application.yml 기본 설정 변경
> Chore: prod 설정

- src/main/java/com/teamddd/duckmap/repository/ReviewRepository.java
- src/test/java/com/teamddd/duckmap/repository/ReviewRepositoryTest.java
> EventId로 review 목록 조회
- ReviewRepository
- ReviewRepositoryTest
> Feat: #128 - EventId로 review 목록 조회

- src/main/java/com/teamddd/duckmap/repository/ReviewRepository.java
- src/main/java/com/teamddd/duckmap/repository/ReviewRepositoryCustom.java
- src/main/java/com/teamddd/duckmap/repository/ReviewRepositoryImpl.java
- src/test/java/com/teamddd/duckmap/repository/ReviewRepositoryTest.java
> artistId, date로 리뷰 목록 조회
- ReviewRepository
- ReviewRepositoryCustom
- ReviewRepositoryImpl
- ReviewRepositoryTest
> Feat: #127 - artistId, date로 리뷰 목록 조회

- src/main/java/com/teamddd/duckmap/controller/BookmarkFolderController.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkFolderUserRes.java
- src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryCustom.java
- src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryImpl.java
- src/test/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryTest.java
> 북마크 폴더 pk로 북마크 폴더 조회시 userId, username 반환
- BookmarkFolderUserRes
- BookmarkFolderUserDto
- BookmarkFolderRepository
- BookmarkFolderRepositoryCustom
- BookmarkFolderRepositoryImpl
- BookmarkFolderRepositoryTest
- BookmarkFolderController
- BookmarkFolderUserDto는 실수로 repository에 push됨
> Feat: #126 -북마크 폴더 pk로 북마크 폴더 조회시 userId, username 반환

- build.gradle
> Spring Security 관련 gradle 설정
- build.gradle에 Spring Security, jwt 추가
> Chore: Spring Security 관련 gradle 설정

- src/main/java/com/teamddd/duckmap/controller/AuthController.java
- src/main/java/com/teamddd/duckmap/dto/user/auth/LoginUserRes.java
> 프론트엔드 요청: 로그인시 mock-api 테스트용 임의 토큰값 반환
- LoginUserRes
- String token
> Refactor: 로그인시 mock-api 테스트용 임의 토큰값 반환

- build.gradle
Reverts duck-map-project/duck-map-be#138
> Revert "Chore: Spring Security 관련 gradle 설정"

- src/main/java/com/teamddd/duckmap/controller/AuthController.java
> Fix: RequestBody import 수정

- .gitignore
> test용 yml, 개발용 sql file gitignore 추가
- .gitignore
> Chore: test용 yml, sql 추가

- src/main/java/com/teamddd/duckmap/DuckmapApplication.java
> Spring Security 로그인 화면 제거 설정 삭제
> Refactor: Spring Security 로그인 화면 제거 설정 삭제

- src/main/java/com/teamddd/duckmap/entity/Member.java
> Table member로 변경
- Member 엔티티
> Refactor: Table member로 변경

- src/main/java/com/teamddd/duckmap/config/security/SecurityUser.java
> Spring Security Role 형식 적용
- SecurityUser 생성시 "ROLE_"을 붙여서 role 적용
> Bug: Spring Security Role 형식 적용

- src/main/java/com/teamddd/duckmap/controller/ArtistController.java
- src/main/java/com/teamddd/duckmap/controller/ArtistTypeController.java
- src/main/java/com/teamddd/duckmap/controller/EventCategoryController.java
- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/controller/ImageController.java
> response Result로 감싸지 않고 반환하게 수정
- ArtistController
- ArtistTypeController
- EventCategoryController
- ImageController
> Refactor: response Result로 감싸지 않고 반환하게 수정

- src/main/java/com/teamddd/duckmap/advice/AuthAdvice.java
> method명 exception에 맞게 수정
- AuthAdvice
> Style: method명 exception에 맞게 수정

- src/main/java/com/teamddd/duckmap/config/security/SecurityConfig.java
> SecurityConfig에서 권한 확인 코드 제거
- SecurityConfig
> Feat: #187 - SecurityConfig에서 권한 확인 코드 제거

- src/main/java/com/teamddd/duckmap/advice/AuthAdvice.java
>Authadvice에 invalidMemberException 추가
- Authadvice
> Refactor: Authadvice에 invalidMemberException 추가

- src/main/java/com/teamddd/duckmap/config/security/SecurityConfig.java
>@EnableGlobalMethodSecurity 설정
- SecurityConfig
> Refactor: #186 - @EnableGlobalMethodSecurity 설정

- src/main/java/com/teamddd/duckmap/advice/MemberAdvice.java
- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/exception/DuplicateEmailException.java
- src/main/java/com/teamddd/duckmap/exception/DuplicateUsernameException.java
- src/main/java/com/teamddd/duckmap/service/MemberService.java
> 회원가입 email, username 중복 체크
- MemberAdvice 생성
- DuplicateEmailException
- DuplicateUsernameException
- MemberService
> Feat: #192 - 회원가입 email, username 중복 체크

- src/main/java/com/teamddd/duckmap/controller/ArtistTypeController.java
- src/main/java/com/teamddd/duckmap/dto/artist/ArtistTypeRes.java
- src/main/java/com/teamddd/duckmap/service/ArtistTypeService.java
- src/test/java/com/teamddd/duckmap/service/ArtistTypeServiceTest.java
> artist type 전체 목록 조회 기능 구현 및 api에 적용
- ArtistTypeController
- 페이징 처리를 제거하고 List를 반환하게 변경
- service 기능 적용
- ArtistTypeService getArtistTypes() 구현
- ArtistTypeRes of method 구현
> artist type 전체 목록 조회 기능 구현

- src/main/java/com/teamddd/duckmap/dto/user/CreateMemberReq.java
- src/main/java/com/teamddd/duckmap/dto/user/UpdatePasswordReq.java
> password @Pattern 정규표현식 수정
- UpdatePasswordReq
- CreateMemberReq
> Refactor: password @Pattern 정규표현식 수정

- src/main/java/com/teamddd/duckmap/advice/AuthAdvice.java
- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
> Spring Security auth exception AuthAdvice에 추가
- AuthAdvice에 AuthenticationException, AccessDeniedException 추가
> Feat: #198 - Spring Security auth exception AuthAdvice에 추가

- src/main/java/com/teamddd/duckmap/advice/ApiControllerAdvice.java
> request validation error response 처리를 위해 ApiControllerAdvice 생성
> Feat: request validation error response 처리

- src/main/java/com/teamddd/duckmap/config/redis/RedisRepositoryConfig.java
>Refactor: redisConnectionFactory에 원격 접속을 위한 config 수정
- RedisRepositoryConfig
> Refactor: redisConnectionFactory에 원격 접속을 위한 config 수정

- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
> AuthenticationException message 변경
- enum ExceptionCodeMessage "잘못된 인증입니다"로 변경
> Refactor: AuthenticationException message 변경

- src/test/java/com/teamddd/duckmap/controller/ArtistTypeControllerTest.java
> artist type 전체 목록 조회 api test
> Test: #174 - artist type 전체 목록 조회 api test

- src/main/java/com/teamddd/duckmap/service/ArtistService.java
- src/test/java/com/teamddd/duckmap/service/ArtistServiceTest.java
> artist 저장 기능 구현
- ArtistService
> Feat: #212 - artist 저장 기능 구현

- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/exception/NonExistentArtistTypeException.java
- src/main/java/com/teamddd/duckmap/service/ArtistTypeService.java
- src/test/java/com/teamddd/duckmap/service/ArtistTypeServiceTest.java
> artist type 조회 기능 구현
- ArtistTypeService
> Feat: #218 - artist type 조회 기능 구현

- src/main/java/com/teamddd/duckmap/controller/ArtistTypeController.java
- src/main/java/com/teamddd/duckmap/service/ArtistTypeService.java
- src/test/java/com/teamddd/duckmap/controller/ArtistTypeControllerTest.java
- src/test/java/com/teamddd/duckmap/service/ArtistTypeServiceTest.java
> ArtistTypeService getArtistTypes() 반환값에 맞게 getArtistTypeResList()로 변경
- ArtistTypeService
> Feat: #222 - ArtistTypeService getArtistTypes() 반환값에 맞게 이름 변경

- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/controller/ArtistTypeController.java
- src/main/java/com/teamddd/duckmap/exception/NonExistentArtistTypeException.java
- src/main/java/com/teamddd/duckmap/service/ArtistTypeService.java
- src/test/java/com/teamddd/duckmap/controller/ArtistTypeControllerTest.java
- src/test/java/com/teamddd/duckmap/service/ArtistTypeServiceTest.java
> artist type 조회 기능 구현 및 리팩토링
- artist type 조회 기능 구현
- ArtistTypeControllerTest의 ArtistTypeService MockBean으로 변경
- ArtistTypeService getArtistTypes() 반환값에 맞게 이름 변경
> artist type 조회 기능 구현 및 리팩토링

- src/main/java/com/teamddd/duckmap/dto/artist/ArtistRes.java
- src/main/java/com/teamddd/duckmap/service/ArtistService.java
- src/test/java/com/teamddd/duckmap/dto/artist/ArtistResTest.java
- src/test/java/com/teamddd/duckmap/service/ArtistServiceTest.java
> artist 목록 조회 기능 구현
- ArtistRes.of()
- Artist를 ArtistRes로 변환
- ArtistService
> Feat: #213 - artist 목록 조회 기능 구현

- src/main/java/com/teamddd/duckmap/advice/AuthAdvice.java
- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/exception/InvalidPasswordException.java
- src/main/java/com/teamddd/duckmap/service/MemberService.java
> InvalidPassword Exception 구현
-  InvalidPasswordException 생성
- updatePassword의 exception 변경
> Feat: #234 - InvalidPassword Exception 구현

- src/main/java/com/teamddd/duckmap/controller/ArtistController.java
- src/test/java/com/teamddd/duckmap/controller/ArtistControllerTest.java
> artist 목록 조회 기능 api에 적용
- ArtistController getArtitsts()
> Feat: #213 - artist 목록 조회 기능 api에 적용

- src/main/java/com/teamddd/duckmap/advice/AuthAdvice.java
- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/controller/MemberController.java
- src/main/java/com/teamddd/duckmap/dto/user/DeleteMemberReq.java
- src/main/java/com/teamddd/duckmap/exception/InvalidPasswordException.java
- src/main/java/com/teamddd/duckmap/service/MemberService.java
> 회원 탈퇴 기능 구현
- 회원 탈퇴시 비밀번호 확인
- InvalidPasswordException 예외처리 구현
- 로그아웃 먼저 실행 후 회원 탈퇴
> 회원 탈퇴 기능 구현

- src/main/java/com/teamddd/duckmap/controller/AuthController.java
> Refactor: #230 - 로그인시 리프레시 토큰 redis에만 저장

- src/main/java/com/teamddd/duckmap/config/security/JwtProvider.java
- src/main/java/com/teamddd/duckmap/controller/AuthController.java
- src/main/java/com/teamddd/duckmap/service/AuthService.java
> 재발급시 refresh-token은 redis에서 찾아오도록 로직 수정
- AuthService
- JwtProvider
> Refactor: #231 -  재발급시 refresh-token은 redis에서 찾아오도록 로직 수정

- src/main/java/com/teamddd/duckmap/advice/ServiceAdvice.java
- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/exception/NonExistentFileException.java
- src/main/java/com/teamddd/duckmap/exception/ServiceException.java
- src/main/java/com/teamddd/duckmap/util/FileUtils.java
> image 조회 기능 구현
-  FileUtils 생성
- 존재하지 않는 파일이면 NonExistentFileException 발생 -> nonExistentFileException ExceptionHandler 호출
> Feat: #240 - image 조회 기능 구현

- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/controller/ImageController.java
- src/main/java/com/teamddd/duckmap/exception/NotContentTypeImageException.java
- src/main/java/com/teamddd/duckmap/util/FileUtils.java
> image 저장 기능 구현 및 api에 적용
- request content type이 image인지 확인 후 저장
- 파일 저장시 UUID로 파일명 변경 후 저장
> Feat: #245 - image 저장 기능 구현

- src/main/java/com/teamddd/duckmap/service/ArtistService.java
- src/test/java/com/teamddd/duckmap/service/ArtistServiceTest.java
> 소속 artist 목록 조회 기능 구현
- ArtistServcie getArtistsByGroup()
> Feat: #214 - 소속 artist 목록 조회 기능 구현

- src/main/java/com/teamddd/duckmap/controller/ArtistController.java
- src/test/java/com/teamddd/duckmap/controller/ArtistControllerTest.java
> 소속 artist 목록 조회 api 생성
- ArtistController에 getArtistsByGroup() 생성
> Feat: #214 - 소속 artist 목록 조회 api 생성

- src/main/java/com/teamddd/duckmap/controller/EventCategoryController.java
- src/test/java/com/teamddd/duckmap/controller/EventCategoryControllerTest.java
> event category 저장 기능 api에 적용
- EventCategoryController createEventCategory()
> Feat: #256 - event category 저장 기능 api에 적용

- src/main/java/com/teamddd/duckmap/service/SendMailService.java
> Rename: properties 관리 편의를 위한 @Value 수정
- @Value("${props.reset-password-url}")
> Rename: properties 관리 편의를 위한 @Value 수정

- src/main/java/com/teamddd/duckmap/controller/AuthController.java
- src/main/java/com/teamddd/duckmap/dto/user/auth/SendResetPasswordEmailRes.java
- src/main/java/com/teamddd/duckmap/service/AuthService.java
>AuthController 리팩터링
- 누락된 @operation 추가 및 예외처리 리팩터링
- sendResetPassword의 반환타입 변경 및 리팩터링
> AuthController 리팩터링

- src/main/java/com/teamddd/duckmap/advice/AuthAdvice.java
- src/main/java/com/teamddd/duckmap/controller/MemberController.java
- src/main/java/com/teamddd/duckmap/service/MemberService.java
> Member Service 리팩터링
- invalidPasswordException의 ResponseStatus BAD_REQUEST 로 수정
- validatePassword 반환값 변경 및 updatePassword 리팩터링
-
> Member Service 리팩터링

- src/test/java/com/teamddd/duckmap/service/ArtistTypeServiceTest.java
> ArtistTypeServiceTest [유효한 값으로 아티스트 타입을 조회한다] error 수정
- ArtistTypeServiceTest getArtistType1() pk 변수로 확인하게 수정
> Test: #284 - ArtistTypeServiceTest [유효한 값으로 아티스트 타입을 조회한다] error 수정

- src/main/java/com/teamddd/duckmap/util/MemberUtils.java
> 로그인 하지 않아도 exception 발생 없이 인증한 Optional 조회하는 기능 구현
- MemberUtils getMember()
> Feat: #281 - 인증한 Optional<Member> 조회 기능 구현

- src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
> EventRepositoryTest user -> member로 변경
- EventRepositoryTest
> Test: #286 - EventRepositoryTest user -> member로 extracting 변경

- src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/ArtistTypeServiceTest.java
> main branch 실패하는 TEST 수정
- #284 
- #286
> 실패하는 TEST 수정

- src/main/java/com/teamddd/duckmap/advice/AuthAdvice.java
- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/exception/AuthenticationRequiredException.java
- src/main/java/com/teamddd/duckmap/util/MemberUtils.java
- src/test/java/com/teamddd/duckmap/service/AuthServiceTest.java
> MemberUtils.getAuthMember() throw exception 변경
> Refactor: MemberUtils.getAuthMember() throw exception 변경

- src/main/java/com/teamddd/duckmap/controller/AuthController.java
- src/main/java/com/teamddd/duckmap/controller/MemberController.java
- src/main/java/com/teamddd/duckmap/dto/user/ResetPasswordReq.java
> 비밀번호 재설정 API 에 @PathVariable 추가
- @PathVariable 추가
- 불필요한 코드 삭제
> Refactor: #291 - 비밀번호 재설정 API에 @PathVariable 추가

- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/exception/NonExistentReviewException.java
> NonExistentReviewException 구현
- NonExistentReviewException 구현
> Feat: #298 - NonExistentReviewException 구현

- src/main/java/com/teamddd/duckmap/controller/ReviewController.java
- src/main/java/com/teamddd/duckmap/dto/review/ReviewRes.java
- src/main/java/com/teamddd/duckmap/service/ReviewService.java
- src/test/java/com/teamddd/duckmap/service/ReviewServiceTest.java
> Review pk로 조회 및 Test 구현
- ReviewController
- getReview() 구현
- ReviewRes
- of() 구현으로 Entity를 Dto로 반환 
- ReviewService
- Entity 반환하는 단건 조회 getReview() 구현
- Dto 반환하는 단건 조회 getReviewById() 구현
- 리뷰 조회 test 구현
> Review pk로 조회 및 Test 구현

- src/main/java/com/teamddd/duckmap/controller/ReviewController.java
- src/main/java/com/teamddd/duckmap/service/ReviewService.java
- src/test/java/com/teamddd/duckmap/service/ReviewServiceTest.java
> Review Service의 모호한 메서드명을 변경 
- getReviewById -> getReviewRes로 변경
> Rename: #307 - getReviewById를 getReviewRes로 변경

- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventRes.java
- src/main/java/com/teamddd/duckmap/entity/Event.java
- src/main/java/com/teamddd/duckmap/exception/NonExistentEventCategoryException.java
- src/main/java/com/teamddd/duckmap/exception/NonExistentEventException.java
- src/main/java/com/teamddd/duckmap/repository/ArtistRepository.java
- src/main/java/com/teamddd/duckmap/repository/EventCategoryRepository.java
- src/main/java/com/teamddd/duckmap/repository/ReviewRepository.java
- src/main/java/com/teamddd/duckmap/service/ArtistService.java
- src/main/java/com/teamddd/duckmap/service/EventCategoryService.java
- src/main/java/com/teamddd/duckmap/service/EventService.java
- src/main/java/com/teamddd/duckmap/util/MemberUtils.java
- src/test/java/com/teamddd/duckmap/repository/ArtistRepositoryTest.java
- src/test/java/com/teamddd/duckmap/repository/EventCategoryRepositoryTest.java
- src/test/java/com/teamddd/duckmap/repository/ReviewRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/ArtistServiceTest.java
- src/test/java/com/teamddd/duckmap/service/EventCategoryServiceTest.java
- src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> Event 등록 및 상세 조회 기능 구현
- EventService createEvent()
- EventService getEventRes()
> Event 등록 및 상세 조회 기능 구현

- src/main/java/com/teamddd/duckmap/entity/Event.java
- src/main/java/com/teamddd/duckmap/service/EventService.java
- src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> Event 생성 시 중간 테이블 저장 오류 수정
- EventArtist build시 event 입력하게 수정
- EventInfoCategory build시 event 입력하게 수정
- EventImage build시 thumbnail 값 입력하게 수정
> Feat: #313 - Event 생성 시 중간 테이블 저장 오류 수정

- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventRes.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventsRes.java
- src/main/java/com/teamddd/duckmap/service/EventService.java
> EventRes boolean like, bookmark를 pk 반환으로 변경
- EventRes, EventsRes boolean like, bookmark를 pk 반환으로 변경
> Feat: #306 - EventRes boolean like, bookmark를 pk 반환으로 변경

- src/main/java/com/teamddd/duckmap/entity/Review.java
- src/main/java/com/teamddd/duckmap/service/ReviewService.java
- src/test/java/com/teamddd/duckmap/service/ReviewServiceTest.java
> Review 생성시 ReviewImage build 수정
- Review 엔티티에 @Builder.Default 추가
- ArrayList로 초기화 하기 위함 
- ReviewImage build할 때 review 객체를 할당하도록 수정
- createReview() Test에서 ReviewImage 생성 확인
> Fix: #315 - Review 생성시 ReviewImage build 수정

- src/main/java/com/teamddd/duckmap/entity/Review.java
- src/main/java/com/teamddd/duckmap/service/ReviewService.java
- src/test/java/com/teamddd/duckmap/service/ReviewServiceTest.java
> Review 등록 수정
- Review 엔티티에 @Builder.Default 추가
- ArrayList로 초기화 하기 위함 
- ReviewImage build할 때 review 객체를 할당하도록 수정
- createReview() Test에서 ReviewImage 생성 확인
> Review 등록 기능 수정

- src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> EventRes boolean like, bookmark를 pk 반환으로 Test 변경
> Feat: #306 - EventRes boolean like, bookmark를 pk 반환으로 Test 변경

- .github/workflows/build-test.yml
- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventSearchParam.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventSearchServiceReq.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventsRes.java
- src/main/java/com/teamddd/duckmap/service/EventService.java
- src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> artist, 날짜 기준 event 목록 조회 기능 구현
- EventSearchParam inProgress를 onlyInProgress로 명확하게 변경
- EventService getEventsResList() 구현
- EventsRes of() 구현
- .github/workflows/build-test.yml 기능 구현과 무관하지만 test 실행이 안돼서 수정했습니다
> artist, 날짜 기준 event 목록 조회 기능 구현

- .github/workflows/build-test.yml
- .github/workflows/ci-cd.yml
> test application.yml 생성 시 mkdir resources 과정 추가하게 수정
> test application.yml 생성 시 mkdir resources 과정 추가

- src/main/java/com/teamddd/duckmap/controller/BookmarkFolderController.java
- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
- src/test/java/com/teamddd/duckmap/service/BookmarkFolderServiceTest.java
> 북마크 폴더 생성 구현
- BookmarkFolderController
- BookmarkFolderService
- BookmarkFolderServiceTest
> Feat: #296 - 북마크 폴더 생성 구현

- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/controller/BookmarkFolderController.java
- src/main/java/com/teamddd/duckmap/entity/EventBookmarkFolder.java
- src/main/java/com/teamddd/duckmap/exception/NonExistentBookmarkFolderException.java
- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
- src/test/java/com/teamddd/duckmap/service/BookmarkFolderServiceTest.java
> 북마크 폴더명, 이미지 변경 구현
- BookmarkFolder에 UpdateBookmarkFolder() 구현
- BookmarkFolderService에 updateBookmarkFolder() 구현
- BookmarkFolderController에 updateBookmarkFolder() 구현
- NonExistentBookmarkFolderException 구현
- 북마크 폴더명, 이미지 변경 Test 구현
> Feat: #334 - 북마크 폴더명, 이미지 변경 구현

- src/main/java/com/teamddd/duckmap/controller/BookmarkFolderController.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkFolderMemberRes.java
- src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryCustom.java
- src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryImpl.java
- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
- src/test/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/BookmarkFolderServiceTest.java
> 북마크 폴더 pk로 북마크 폴더,사용자 정보 조회 구현
- BookmarkFolderMemberRes를 반환하는 of() 구현
- BookmarkFolderService에 getBookmarkFolderMemberRes() 구현
- 북마크 폴더 pk로 북마크 폴더,사용자 정보 조회 Test 구현
> Feat: #332 - 북마크 폴더 pk로 북마크 폴더,사용자 정보 조회 구현

- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/controller/BookmarkFolderController.java
- src/main/java/com/teamddd/duckmap/entity/EventBookmarkFolder.java
- src/main/java/com/teamddd/duckmap/exception/NonExistentBookmarkFolderException.java
- src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryCustom.java
- src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryImpl.java
- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
- src/test/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/BookmarkFolderServiceTest.java
> 북마크 폴더 생성, PK로 조회, 이름 및 이미지 변경 기능 구현
- #335
- #336 
- #337 
> 북마크 폴더 목록 조회는 북마크 기능 구현 후 진행 예정
> 북마크 폴더 생성, PK로 조회, 이름 및 이미지 변경 기능 구현

- src/main/java/com/teamddd/duckmap/dto/event/event/EventLikeBookmarkDto.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventsRes.java
- src/main/java/com/teamddd/duckmap/repository/EventRepositoryImpl.java
- src/main/java/com/teamddd/duckmap/service/EventService.java
- src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
> EventLikeBookmarkDto EventLike, EventBookmark 반환에서 pk 반환으로 변경
- EventLikeBookmarkDto
- EventRepositoryImpl
> Feat: #328 - EventLikeBookmarkDto EventLike, EventBookmark pk 반환으로 변경

- src/main/java/com/teamddd/duckmap/advice/EventAdvice.java
- src/main/java/com/teamddd/duckmap/advice/MemberAdvice.java
- src/main/java/com/teamddd/duckmap/advice/ReviewAdvice.java
- src/main/java/com/teamddd/duckmap/advice/ServiceAdvice.java
> 누락된 @ExceptionHandler 생성
- EventAdvice
- NonExistentEventLikeException
- NonExistentBookmarkFolderException
- ReviewAdvice
- NonExistentReviewException
> Feat: #341 - 누락된 @ExceptionHandler 생성

- src/main/java/com/teamddd/duckmap/advice/ArtistAdvice.java
- src/main/java/com/teamddd/duckmap/advice/EventAdvice.java
- src/main/java/com/teamddd/duckmap/advice/MemberAdvice.java
- src/main/java/com/teamddd/duckmap/advice/ReviewAdvice.java
- src/main/java/com/teamddd/duckmap/advice/ServiceAdvice.java
> 누락된 @ExceptionHandler 생성 완료
- 누락된 @ExceptionHandler main에 적용
> 누락된 @ExceptionHandler 생성 완료

- src/main/java/com/teamddd/duckmap/advice/EventAdvice.java
- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/controller/BookmarkController.java
- src/main/java/com/teamddd/duckmap/exception/NonExistentBookmarkException.java
- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
- src/main/java/com/teamddd/duckmap/service/BookmarkService.java
- src/test/java/com/teamddd/duckmap/service/BookmarkServiceTest.java
>북마크 생성, 삭제 기능 구현
- NonExistentBookmarkException 구현
- BookmarkFolderService
- getEventBookmarkFolder
- BookmarkController
- createBookmark 북마크 생성
- deleteBookmark 북마크 삭제(취소) 
- BookmarkService
- createBookmark 북마크 생성
- deleteBookmark 북마크 삭제시 로그인한 회원과 북마크한 회원이 같은지 확인
- getEventBookmark
- BookmarkServiceTest
> Feat: #333 - 북마크 생성, 삭제 기능 구현

- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventSearchParam.java
- src/main/java/com/teamddd/duckmap/service/EventService.java
> Event 목록 조회 api param null 가능하게 수정
- EventSearchParam
- onlyInProgress값 null -> false 변환
- EventService
- artistId null이 아닌 경우만 Artist 확인
> Feat: #344 - Event 목록 조회 api param null 가능하게 수정

- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/dto/event/event/MyEventsServiceReq.java
- src/main/java/com/teamddd/duckmap/service/EventService.java
- src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> 생성자 기준 event 목록 조회 기능 구현
- EventService getMyEventsRes()
> Feat: #348 - 생성자 기준 event 목록 조회 기능 구현

- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/dto/event/event/MyLikeEventsServiceReq.java
- src/main/java/com/teamddd/duckmap/service/EventService.java
- src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> 로그인한 회원이 좋아요한 event 목록 조회 기능 구현
- EventService getMyLikeEventsRes()
> Feat: #356 - 좋아요 기준 event 목록 조회 기능 구현

- src/main/java/com/teamddd/duckmap/controller/ReviewController.java
- src/main/java/com/teamddd/duckmap/dto/review/MyReviewServiceReq.java
- src/main/java/com/teamddd/duckmap/dto/review/MyReviewsRes.java
- src/main/java/com/teamddd/duckmap/dto/review/ReviewEventDto.java
- src/main/java/com/teamddd/duckmap/repository/ReviewRepositoryCustom.java
- src/main/java/com/teamddd/duckmap/repository/ReviewRepositoryImpl.java
- src/main/java/com/teamddd/duckmap/service/ReviewService.java
- src/test/java/com/teamddd/duckmap/repository/ReviewRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/ReviewServiceTest.java
> 나의 Review 목록 조회 구현
-  MyReviewServiceReq 생성
-  MyReviewsRes 
- of() 구현
- ReviewEventDto 생성
- ReviewRepositoryImpl
- findWithEventByMemberId() 구현
- ReviewService, ReviewController
- getMyReviewsRes(), getMyReviews() 구현
- ReviewRepositoryTest 
- findWithEventByMemberId() Test 작성
- getMyReviewsRes() Test 작성
> Feat: #300 - 나의 Review 목록 조회 구현

- src/main/java/com/teamddd/duckmap/controller/ArtistTypeController.java
- src/main/java/com/teamddd/duckmap/dto/artist/UpdateArtistTypeServiceReq.java
- src/main/java/com/teamddd/duckmap/entity/ArtistType.java
- src/main/java/com/teamddd/duckmap/service/ArtistTypeService.java
- src/test/java/com/teamddd/duckmap/service/ArtistTypeServiceTest.java
> artist type 수정 기능 구현
- ArtistTypeService updateArtistType()
- ArtistType updateArtistType()
> Feat: #175 - artist type 수정 기능 구현

- src/main/java/com/teamddd/duckmap/controller/BookmarkFolderController.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkFolderRes.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/MyBookmarkFolderServiceReq.java
- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
- src/test/java/com/teamddd/duckmap/service/BookmarkFolderServiceTest.java
>  로그인한 회원이 생성한 북마크 폴더 목록 조회 구현
- BookmarkFolderRes of() 구현
- MyBookmarkFolderServiceReq 생성
- BookmarkFolderController, BookmarkFolderService
- getMyBookmarkFolderRes(), getMyBookmarkFolders() 구현 
- BookmarkFolderServiceTest
- getMyBookmarkFolders() Test 작성
> Feat: #362 - 로그인한 회원이 생성한 북마크 폴더 목록 조회 구현

- src/main/java/com/teamddd/duckmap/advice/ArtistAdvice.java
- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/controller/ArtistTypeController.java
- src/main/java/com/teamddd/duckmap/exception/UnableToDeleteArtistTypeInUseException.java
- src/main/java/com/teamddd/duckmap/repository/ArtistRepository.java
- src/main/java/com/teamddd/duckmap/service/ArtistTypeService.java
- src/test/java/com/teamddd/duckmap/repository/ArtistRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/ArtistTypeServiceTest.java
> artist type 삭제 기능 구현
- ArtistTypeService deleteArtistType()
- ArtistRepository countByArtistType()
> Feat: #176 - artist type 삭제 기능 구현

- src/main/java/com/teamddd/duckmap/controller/BookmarkFolderController.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkEventDto.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkFolderRes.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkedEventRes.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkedEventsServiceReq.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/MyBookmarkFolderServiceReq.java
- src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryImpl.java
- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
- src/test/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/BookmarkFolderServiceTest.java
> 로그인한 회원이 생성한 북마크 폴더 목록 조회, 북마크 폴더 내부의 이벤트 목록 조회 구현
- #362 
- #363
> 로그인한 회원이 생성한 북마크 폴더 목록 조회, 북마크 폴더 내부의 이벤트 목록 조회 구현

- src/main/java/com/teamddd/duckmap/controller/ArtistTypeController.java
- src/test/java/com/teamddd/duckmap/controller/ArtistTypeControllerTest.java
> ArtistType 수정, 삭제 api 관리자 권한 확인 추가
- ArtistTypeController updateArtistType(), deleteArtistType()
- ArtistTypeController '아티스트 타입 pk로 조회' api 제거
> Feat: #371 - ArtistType 수정, 삭제 api 관리자 권한 확인 추가

- src/main/java/com/teamddd/duckmap/controller/ReviewController.java
- src/main/java/com/teamddd/duckmap/service/ReviewService.java
- src/test/java/com/teamddd/duckmap/service/ReviewServiceTest.java
> Review 삭제 구현
- ReviewController, ReviewService
- 추후에 서버에서 리뷰 이미지 삭제 로직 추가해야 함
> Feat: #380 - Review 삭제 구현

- src/main/java/com/teamddd/duckmap/controller/ArtistController.java
- src/main/java/com/teamddd/duckmap/dto/artist/UpdateArtistServiceReq.java
- src/main/java/com/teamddd/duckmap/entity/Artist.java
- src/main/java/com/teamddd/duckmap/service/ArtistService.java
- src/main/java/com/teamddd/duckmap/util/FileUtils.java
- src/test/java/com/teamddd/duckmap/controller/ArtistControllerTest.java
- src/test/java/com/teamddd/duckmap/service/ArtistServiceTest.java
> artist 수정 기능 구현
- FileUtils deleteFile()
- ArtistService updateArtist()
- ArtistController updateArtist()
> Feat: #385 - artist 수정 기능 구현

- src/main/java/com/teamddd/duckmap/controller/ArtistController.java
- src/main/java/com/teamddd/duckmap/repository/ArtistRepository.java
- src/main/java/com/teamddd/duckmap/repository/LastSearchArtistRepository.java
- src/main/java/com/teamddd/duckmap/service/ArtistService.java
- src/test/java/com/teamddd/duckmap/controller/ArtistControllerTest.java
- src/test/java/com/teamddd/duckmap/repository/ArtistRepositoryTest.java
- src/test/java/com/teamddd/duckmap/repository/LastSearchArtistRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/ArtistServiceTest.java
> artist 삭제 기능 구현
- ArtistService deleteArtist()
- 해당 Artist group fk로 갖는 경우 null로 변경
- LastSearchArtist artist fk로 갖는 경우 삭제
- image file 삭제
- ArtistRepository bulkGroupToNull()
- LastSearchArtistRepository deleteByArtistId()
> Feat: #386 - artist 삭제 기능 구현

- src/main/java/com/teamddd/duckmap/entity/ArtistType.java
> ArtistType에 BaseByEntity 적용
- ArtistType
> Feat: #388 - ArtistType에 BaseByEntity 적용

- src/main/java/com/teamddd/duckmap/controller/ArtistController.java
- src/main/java/com/teamddd/duckmap/dto/artist/UpdateArtistServiceReq.java
- src/main/java/com/teamddd/duckmap/entity/Artist.java
- src/main/java/com/teamddd/duckmap/entity/ArtistType.java
- src/main/java/com/teamddd/duckmap/repository/ArtistRepository.java
- src/main/java/com/teamddd/duckmap/repository/LastSearchArtistRepository.java
- src/main/java/com/teamddd/duckmap/service/ArtistService.java
- src/main/java/com/teamddd/duckmap/util/FileUtils.java
- src/test/java/com/teamddd/duckmap/controller/ArtistControllerTest.java
- src/test/java/com/teamddd/duckmap/repository/ArtistRepositoryTest.java
- src/test/java/com/teamddd/duckmap/repository/LastSearchArtistRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/ArtistServiceTest.java
> Artist 수정, 삭제 기능 구현
- 파일 삭제 Util 기능 구현
- #385 
- #386
> Artist 수정, 삭제 기능 구현

- src/main/java/com/teamddd/duckmap/service/MemberService.java
>  Member 수정 및 삭제시 서버에서 Member의 프로필 이미지 삭제 구현
- MemberService
- updateMemberInfo, deleteMember
> Feat: #365 - Member 수정 및 삭제시 서버에서 Member의 프로필 이미지 삭제 구현

- src/main/java/com/teamddd/duckmap/controller/ReviewController.java
- src/main/java/com/teamddd/duckmap/service/ReviewService.java
- src/test/java/com/teamddd/duckmap/service/ReviewServiceTest.java
> Feat: #366, #380 - 리뷰 삭제 기능 구현

- src/main/java/com/teamddd/duckmap/controller/ReviewController.java
- src/main/java/com/teamddd/duckmap/entity/Review.java
- src/main/java/com/teamddd/duckmap/service/ReviewService.java
- src/test/java/com/teamddd/duckmap/service/ReviewServiceTest.java
> Review 수정 구현
- Review 
- updateReview()
- ReviewController, ReviewService
- 수정된 imageList에 oldimage가 없으면 서버에서 이미지를 삭제 
> Feat: #379 - Review 수정 구현

- src/main/java/com/teamddd/duckmap/controller/BookmarkFolderController.java
- src/main/java/com/teamddd/duckmap/repository/BookmarkRepository.java
- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
- src/test/java/com/teamddd/duckmap/repository/BookmarkRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/BookmarkFolderServiceTest.java
> 북마크 폴더 삭제 구현
- BookmarkFolderController, BookmarkFolderService
- BookmarkRepository
- deleteByBookmarkFolderId 구현
- BookmarkFolderServiceTest
> Feat: #387 - 북마크 폴더 삭제 구현

- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
- src/test/java/com/teamddd/duckmap/service/BookmarkFolderServiceTest.java
> Fix: ImageRes import 제거

- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
> 북마크폴더 수정시 서버에서 기존 북마크 폴더 image 삭제
- updateBookmarkFolder() 로직 수정
> Feat: #402 - 북마크폴더 수정시 서버에서 기존 북마크 폴더 image 삭제

- src/main/java/com/teamddd/duckmap/entity/EventBookmarkFolder.java
> 누락된 @Builder.Default 추가
- EventBookmarkFolder
> Feat: #407 - 누락된 @Builder.Default 추가

- src/main/java/com/teamddd/duckmap/entity/EventBookmarkFolder.java
- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
> 북마크 폴더 리팩토링

- src/main/java/com/teamddd/duckmap/controller/EventCategoryController.java
- src/main/java/com/teamddd/duckmap/dto/event/category/UpdateEventCategoryServiceReq.java
- src/main/java/com/teamddd/duckmap/entity/EventCategory.java
- src/main/java/com/teamddd/duckmap/service/EventCategoryService.java
- src/test/java/com/teamddd/duckmap/controller/EventCategoryControllerTest.java
- src/test/java/com/teamddd/duckmap/service/EventCategoryServiceTest.java
> event category 수정 기능 구현
- EventCategoryService updateEventCategory()
- EventCategory updateEventCategory()
- EventCategoryController updateEventCategory()
> Feat: #414 - event category 수정 기능 구현

- src/main/java/com/teamddd/duckmap/advice/EventAdvice.java
> UnableToDeleteEventCategoryInUseException advice 추가
- EventAdvice unableToDeleteEventCategoryInUseException()
> UnableToDeleteEventCategoryInUseException advice 추가

- src/main/java/com/teamddd/duckmap/advice/EventAdvice.java
- src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java
- src/main/java/com/teamddd/duckmap/controller/EventCategoryController.java
- src/main/java/com/teamddd/duckmap/dto/event/category/UpdateEventCategoryServiceReq.java
- src/main/java/com/teamddd/duckmap/entity/EventCategory.java
- src/main/java/com/teamddd/duckmap/exception/UnableToDeleteEventCategoryInUseException.java
- src/main/java/com/teamddd/duckmap/repository/EventInfoCategoryRepository.java
- src/main/java/com/teamddd/duckmap/service/EventCategoryService.java
- src/test/java/com/teamddd/duckmap/controller/EventCategoryControllerTest.java
- src/test/java/com/teamddd/duckmap/repository/EventInfoCategoryRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/EventCategoryServiceTest.java
> EventCategory 수정, 삭제 기능 구현
- #414
- #415
> EventCategory 수정, 삭제 기능 구현

- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/dto/event/event/UpdateEventReq.java
- src/main/java/com/teamddd/duckmap/dto/event/event/UpdateEventServiceReq.java
- src/main/java/com/teamddd/duckmap/entity/Event.java
- src/main/java/com/teamddd/duckmap/repository/EventArtistRepository.java
- src/main/java/com/teamddd/duckmap/repository/EventImageRepository.java
- src/main/java/com/teamddd/duckmap/service/EventService.java
- src/test/java/com/teamddd/duckmap/repository/EventArtistRepositoryTest.java
- src/test/java/com/teamddd/duckmap/repository/EventImageRepositoryTest.java
- src/test/java/com/teamddd/duckmap/repository/EventInfoCategoryRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> event 수정 기능 구현
- EventController updateEvent()
- EventService updateEvent()
- EventArtistRepository deleteByEventId()
- EventInfoCategoryRepository deleteByEventId()
- EventImageRepository deleteByEventId()
- Event updateEvent()
> Feat: #423 - event 수정 기능 구현

- src/main/java/com/teamddd/duckmap/config/audit/AuditorAwareImpl.java
> 회원가입시 오류 발생하여 긴급 수정
- AuditorAwareImpl 코드 수정
> !HOTFIX: AuditorAwareImpl 코드 수정

- src/main/java/com/teamddd/duckmap/controller/EventController.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventLikeReviewCountDto.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventPageReq.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventsMapRes.java
- src/main/java/com/teamddd/duckmap/dto/event/event/HashtagRes.java
- src/main/java/com/teamddd/duckmap/entity/EventArtist.java
- src/main/java/com/teamddd/duckmap/repository/EventRepository.java
- src/main/java/com/teamddd/duckmap/repository/EventRepositoryCustom.java
- src/main/java/com/teamddd/duckmap/repository/EventRepositoryImpl.java
- src/main/java/com/teamddd/duckmap/service/EventService.java
- src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> 해시태그, 지도 표기용 Event 목록 조회 기능 구현
- #422 
- #436
> 해시태그, 지도 표기용 Event 목록 조회 기능 구현

- src/main/java/com/teamddd/duckmap/DuckmapApplication.java
- src/main/java/com/teamddd/duckmap/config/web/CorsConfig.java
> Feat: CORS 설정을 위한 Bean 등록

- src/main/java/com/teamddd/duckmap/service/MemberService.java
>  회원 정보 수정시 닉네임 중복체크 로직 추가
- updateMemberInfo()에 checkDuplicateUsername() 추가
-
> Feat: #442 - 회원 정보 수정시 닉네임 중복체크 로직 추가

- src/main/java/com/teamddd/duckmap/controller/MemberController.java
- src/main/java/com/teamddd/duckmap/dto/user/LastSearchArtistRes.java
- src/main/java/com/teamddd/duckmap/repository/LastSearchArtistRepository.java
- src/main/java/com/teamddd/duckmap/service/LastSearchArtistService.java
- src/test/java/com/teamddd/duckmap/repository/LastSearchArtistRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/LastSearchArtistServiceTest.java
> LastSearchArtist 조회 기능 구현
- MemberController getLastSearchArtist()
- LastSearchArtistRes
- LastSearchArtistService getLastSearchArtistRes()
- LastSearchArtistRepository findWithArtistByMember()
> Feat: #421 - LastSearchArtist 조회 기능 구현

- src/main/java/com/teamddd/duckmap/config/web/CorsConfig.java
> !HOTFIX: allowCredentials 옵션 추가

- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
> 북마크 폴더 수정, 삭제시 서버 이미지 삭제하지 않도록 로직 수정
> Refactor: #447 - 북마크 폴더 수정, 삭제시 서버 이미지 삭제하지 않도록 로직 수정

- src/main/java/com/teamddd/duckmap/repository/EventRepositoryImpl.java
- src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
> 이벤트 목록 조회 시 아티스트가 있는 이벤트만 조회되게 수정
- EventRepository findByArtistAndDate(), findForMap()
> Feat: #454 - 이벤트 목록 조회 시 아티스트가 있는 이벤트만 조회되게 수정

- src/main/java/com/teamddd/duckmap/repository/ArtistRepository.java
- src/main/java/com/teamddd/duckmap/repository/EventArtistRepository.java
- src/main/java/com/teamddd/duckmap/service/ArtistService.java
- src/test/java/com/teamddd/duckmap/repository/ArtistRepositoryTest.java
- src/test/java/com/teamddd/duckmap/repository/EventArtistRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/ArtistServiceTest.java
> Artist 제거 시 EventArtist의 artist를 null로 변경
- EventArtistRepository updateArtistToNull()
- ArtistService deleteArtist()
- ArtistRepository method명 변경 bulkGroupToNull() -> updateGroupToNull()
> Feat: #458 - Artist 제거 시 EventArtist null로 변경

- src/main/java/com/teamddd/duckmap/entity/EventArtist.java
- src/main/java/com/teamddd/duckmap/repository/EventRepositoryImpl.java
- src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> Artist 제거 시 null로 변경되어 fk 제약조건 제약을 받지 않아 foreignKey 설정이 불필요하다
- EventArtist artist
> Feat: #460 - EventArtist artist foreignKey 설정 제거

- src/main/java/com/teamddd/duckmap/entity/EventArtist.java
- src/main/java/com/teamddd/duckmap/repository/ArtistRepository.java
- src/main/java/com/teamddd/duckmap/repository/ArtistRepositoryImpl.java
- src/main/java/com/teamddd/duckmap/repository/EventArtistRepository.java
- src/main/java/com/teamddd/duckmap/repository/EventRepositoryImpl.java
- src/main/java/com/teamddd/duckmap/service/ArtistService.java
- src/test/java/com/teamddd/duckmap/repository/ArtistRepositoryTest.java
- src/test/java/com/teamddd/duckmap/repository/EventArtistRepositoryTest.java
- src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
- src/test/java/com/teamddd/duckmap/service/ArtistServiceTest.java
- src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> Artist 관련 수정 사항
- #444 
- #454 
- #458 
- #460
> Artist 관련 수정 사항

- src/main/java/com/teamddd/duckmap/repository/ArtistRepositoryImpl.java
- src/main/java/com/teamddd/duckmap/service/ArtistService.java
- src/test/java/com/teamddd/duckmap/service/ArtistServiceTest.java
> ArtistRepository.findByTypeAndName() fetch join 적용
- ArtistRepository findByTypeAndName()
- ArtistService getArtistResPageByTypeAndName() 리팩토링
> Feat: #462 - ArtistRepository.findByTypeAndName() fetch join 적용

- src/main/java/com/teamddd/duckmap/repository/ArtistRepository.java
- src/main/java/com/teamddd/duckmap/service/ArtistService.java
- src/test/java/com/teamddd/duckmap/service/ArtistServiceTest.java
> ArtistRepository.findByGroup() fetch join 적용
- ArtistRepository findByGroup()
- ArtistService getArtistsByGroup() 리팩토링
#468 commit message 잘못됐어요
> Feat: #468 - ArtistRepository.findByGroup() fetch join 적용

- src/main/java/com/teamddd/duckmap/controller/BookmarkFolderController.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkFolderMemberRes.java
- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
- src/test/java/com/teamddd/duckmap/service/BookmarkFolderServiceTest.java
> 북마크 폴더 외부 공유 API에서 북마크된 이벤트 목록도 반환하도록 수정
- BookmarkFolderController
- BookmarkFolderService
- BookmarkFolderMemberRes
- BookmarkFolderServiceTest
> Feat: #472 - 북마크 폴더 외부 공유 API에서 북마크된 이벤트 목록도 반환하도록 수정

- Dockerfile
- build.gradle
> java version 11에서 17로 변경
- build.gradle
- Dockerfile
> Feat: #474 - java version 11에서 17로 변경

- src/main/java/com/teamddd/duckmap/controller/BookmarkFolderController.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkFolderMemberRes.java
- src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java
- src/test/java/com/teamddd/duckmap/service/BookmarkFolderServiceTest.java
> 북마크 폴더 외부 공유 API 수정

- src/main/java/com/teamddd/duckmap/config/test/WithMockAuthUser.java
- src/main/java/com/teamddd/duckmap/config/test/WithMockAuthUserSecurityContextFactory.java
> ControllerTest를 위한 MockAuthUser 생성
- WithMockAuthUser
- WithMockAuthUserSecurityContextFactory
> Feat: #471 - ControllerTest를 위한 MockAuthUser 생성

- src/test/java/com/teamddd/duckmap/controller/LikeControllerTest.java
> 누락된 LikeController Test 작성
- LikeControllerTest
> Feat: #355 - 누락된 LikeController Test 작성

- .github/workflows/build-test.yml
- .github/workflows/ci-cd.yml
- .github/workflows/close-issue.yml
> WithMockAuthUser 생성 및 LikeController 테스트코드 작성
- #355 
- #471
> WithMockAuthUser 생성 및 LikeController 테스트코드 작성

- src/main/java/com/teamddd/duckmap/controller/MemberController.java
- src/main/java/com/teamddd/duckmap/service/MemberService.java
> MemberUtils.getAuthMember().getUsername()를 Controller에서 호출
- MemberService
- MemberController
> Feat: #485 - MemberUtils.getAuthMember().getUsername()를 Controller에서 호출

- src/main/java/com/teamddd/duckmap/controller/MemberController.java
- src/main/java/com/teamddd/duckmap/service/MemberService.java
- src/test/java/com/teamddd/duckmap/service/MemberServiceTest.java
> MemberServiceTest 코드 작성
- deleteMember()
- validatePassword() 
- updatePassword()
- updateMemberInfo()
- getMyInfoBySecurity()
> Feat: #483 - MemberServiceTest 코드 작성

- .github/workflows/build-test.yml
- .github/workflows/ci-cd.yml
- .github/workflows/close-issue.yml
> MemberService 테스트 코드 및 리팩토링
- #483 
- #485
> MemberService 테스트 코드 및 리팩토링

- src/main/java/com/teamddd/duckmap/config/web/CorsConfig.java
> 응답헤더 오류를 해결하기 위해exposedHeaders 설정
> !HOTFIX: exposedHeaders 설정

- src/main/java/com/teamddd/duckmap/config/web/CorsConfig.java
> exposedHeaders 설정(Set-Cookie)
- 프론트에서 RefreshToken을 받기 위한 헤더 설정
> !HOTFIX: exposedHeaders 설정(Set-Cookie)

- src/main/java/com/teamddd/duckmap/controller/AuthController.java
> 도메인이 달라도 쿠키 전송을 가능하게 ResponseCookie.sameSite를 None으로 설정
> !HOTFIX: ResponseCookie.sameSite를 None으로 설정

- src/main/java/com/teamddd/duckmap/controller/AuthController.java
> 쿠키의 domain 설정
- 쿠키의 도메인을 테스트를 위해 프론트 로컬 주소로 설정한다.
> !HOTFIX: 쿠키의 domain 설정

- src/main/java/com/teamddd/duckmap/controller/AuthController.java
> !HOTFIX: 쿠키의 domain 설정 삭제

- .github/workflows/ci-cd.yml
- .gitignore
> https 설정을 위한 ci-cd.yml 수정
- ci-cd.yml 수정
- gitignore에 keystore.p12 추가
> https 설정을 위한 ci-cd.yml 수정

- src/main/java/com/teamddd/duckmap/controller/AuthController.java
> ResponseCookie sameSite를 None으로 설정, secure를 true로 설정
> !HOTFIX: ResponseCookie sameSite를 None으로 설정, secure를 true로 설정

- .github/workflows/ci-cd.yml
> ci-cd.yml 수정
- copy keystore.p12
> !HOTFIX: ci-cd.yml 수정

- src/main/java/com/teamddd/duckmap/controller/MemberController.java
> 회원 정보 수정 api를 PUT 요청에서 PATCH 요청으로 변경
- #505
> !HOTFIX: #505 - 회원 정보 수정 api를 PUT 요청에서 PATCH 요청으로 변경

- src/main/java/com/teamddd/duckmap/controller/MemberController.java
> !HOTFIX: 회원 정보 수정 api를 PUT 요청으로 복구

- src/main/java/com/teamddd/duckmap/service/MemberService.java
> 닉네임이 변경됐을때만 닉네임 중복 체크 하도록 수정
- #508
> !HOTFIX: #508 - 닉네임이 변경됐을때만 닉네임 중복 체크 하도록 수정

- src/main/java/com/teamddd/duckmap/dto/event/event/CreateEventReq.java
- src/main/java/com/teamddd/duckmap/dto/event/event/UpdateEventReq.java
> 이벤트 생성, 수정 request address @NotBlank 제거
- CreateEventReq
- UpdateEventReq
> Feat: #510 - 이벤트 생성, 수정 request address @NotBlank 제거

- src/main/java/com/teamddd/duckmap/dto/event/event/EventsMapRes.java
> 지도 표기용 API response에 address 추가
- EventsMapRes
> Feat: #511 - 지도 표기용 API response에 address 추가

- src/main/java/com/teamddd/duckmap/dto/event/event/CreateEventReq.java
- src/main/java/com/teamddd/duckmap/dto/event/event/EventsMapRes.java
- src/main/java/com/teamddd/duckmap/dto/event/event/UpdateEventReq.java
> Event API request, response 변경
- #510 
- #511
> Event API request, response 변경

- src/main/java/com/teamddd/duckmap/dto/review/ReviewsRes.java
> 리뷰 전체 목록 조회시 아티스트 이름, 카테고리명만 가져오도록 수정
- #520
> Refactor: #520 - 리뷰 전체 목록 조회시 아티스트 이름, 카테고리명만 가져오도록 수정

- src/main/java/com/teamddd/duckmap/repository/ReviewRepositoryImpl.java
> 리뷰 전체 목록 조회시 selectDistinct()
- #524
> Refactor: #524 - 리뷰 전체 목록 조회시 selectDistinct()

- src/main/java/com/teamddd/duckmap/controller/ReviewController.java
- src/main/java/com/teamddd/duckmap/dto/review/ReviewSearchServiceReq.java
- src/main/java/com/teamddd/duckmap/service/ReviewService.java
- src/test/java/com/teamddd/duckmap/service/ReviewServiceTest.java
> 리뷰 목록 조회에서 검색된 아티스트를 member의 lastSearchMember로 저장
- #523
> 리뷰 목록 조회에서 검색된 아티스트를 member의 lastSearchMember로 저장

- src/main/java/com/teamddd/duckmap/service/EventService.java
close: #527
- EventService getEventsResList()
> Fix: #527 - 마지막 검색 아티스트 저장 Transactional 설정

- src/test/java/com/teamddd/duckmap/dto/artist/CreateArtistTypeReqTest.java
- src/test/java/com/teamddd/duckmap/dto/artist/UpdateArtistTypeReqTest.java
close: #530
- CreateArtistTypeReqTest
- UpdateArtistTypeReqTest
> Test: #530 - ArtistType Request domain test 작성

- README.md
> Readme 내용 추가
- 로고, 프로젝트 소개, 서버, ERD, 기술 스택, 팀 소개 추가
- 기능 부분은 상의 및 정리 후 작성
> Docs: Readme 로고, 프로젝트 소개, 서버, ERD, 기술 스택, 팀 소개 추가

- README.md
> Docs: 팀 소개 수정

- src/test/java/com/teamddd/duckmap/dto/artist/ArtistTypeResTest.java
> ArtistType Response domain test 작성
- ArtistTypeResTest
> Feat: #531 - ArtistType Response domain test 작성

- .github/workflows/build-test.yml
- .github/workflows/ci-cd.yml
- src/main/resources/logback-spring.xml
- src/test/resources/logback.xml
> #539
- src/main/resources/logback-spring.xml
- src/test/resources/logback.xml
> logback 설정

- src/main/java/com/teamddd/duckmap/config/security/JwtProvider.java
- src/main/java/com/teamddd/duckmap/config/security/UserDetailsImpl.java
- src/main/java/com/teamddd/duckmap/config/security/UserDetailsServiceImpl.java
- src/main/java/com/teamddd/duckmap/config/test/WithMockAuthUserSecurityContextFactory.java
> Spring Security 설정 코드 리팩토링
close: #543
> Spring Security 설정 코드 리팩토링

- src/main/java/com/teamddd/duckmap/config/web/CorsConfig.java
> 프론트 요청에 따른 CorsConfig 수정
- #547 
- YAML_PROD, YAML_TEST 변경
close: #547
> 프론트 요청에 따른 CorsConfig 수정

- README.md
> Docs: Aws EC2, Docker 추가

- src/main/java/com/teamddd/duckmap/service/ReviewService.java
> #550 
- deleteReview() 누락된 @Transactional 추가
> Refactor: #550 - deleteReview() 누락된 @Transactional 추가

- src/main/java/com/teamddd/duckmap/dto/review/ReviewRes.java
> Review 상세 조회시 수정일 반환 
- ReviewRes에 lastModifiedAt 추가
close #554
> Feat: #554 - ReviewRes에 lastModifiedAt 추가

- src/main/java/com/teamddd/duckmap/service/ArtistService.java
- src/main/java/com/teamddd/duckmap/service/ArtistTypeService.java
- src/main/java/com/teamddd/duckmap/service/EventCategoryService.java
- src/main/java/com/teamddd/duckmap/service/EventService.java
> .collect(Collectors.toList()) -> toList()로 변경
- EventCategoryService
- ArtistService
- ArtistTypeService
- EventService
> Refactor: #557 - .collect(Collectors.toList()) -> toList()로 변경

- src/main/java/com/teamddd/duckmap/dto/event/event/EventRes.java
- src/main/java/com/teamddd/duckmap/service/EventService.java
- src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> 이벤트 상세 조회 시 작성자 pk 반환 추가
- EventRes에 memberId 반환값 추가
- EventService getEventRes
close: #567
> Feat: #567 - 이벤트 상세 조회 시 작성자 pk 반환 추가

- src/test/java/com/teamddd/duckmap/entity/ArtistTest.java
- src/test/java/com/teamddd/duckmap/entity/ArtistTypeTest.java
> Artist 관련 entity Test 작성
- ArtistTest
- ArtistTypeTest
close: #571
> Artist 관련 entity Test 작성

- src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkEventDto.java
- src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkedEventRes.java
> 단순 Dto를 Record Data Class로 변경
- BookmarkedEventRes
- BookmarkEventDto
close: #574
> Refactor: #574 - 단순 Dto를 Record Data Class로 변경

- src/main/java/com/teamddd/duckmap/entity/Report.java
- src/main/java/com/teamddd/duckmap/entity/ReportCode.java
> 설계한 테이블을 바탕으로 ReportCode, Report 엔티티 작성
- ReportCode
- Report 
close #568
> Feat: #568 - ReportCode, Report 엔티티 작성

- src/main/java/com/teamddd/duckmap/controller/AuthController.java
> Hotfix ssl

- src/main/java/com/teamddd/duckmap/config/web/CorsConfig.java
> Config: add delete front HTTP url in CorsConfig
