src/main/java/com/teamddd/duckmap/controller/EventController.java, src/main/java/com/teamddd/duckmap/dto/event/event/EventRes.java, src/main/java/com/teamddd/duckmap/dto/event/event/EventSearchParam.java, src/main/java/com/teamddd/duckmap/dto/event/event/EventsRes.java, src/main/java/com/teamddd/duckmap/dto/event/event/HashtagRes.java
> event 목록 조회 api 생성 & Artist dto import 경로 변경
- GET /events
- GET /events/hashtags/today
- Artist dto import 경로 변경
이벤트 목록 조회 검색 조건은 일단 아티스트, 진행중 여부만 넣었습니다
개발하다가 mock-api랑 병합했더니 artist dto import 에러가 나서 수정했더니 커밋이 지저분해졌네요ㅠㅠ
=> event 목록 조회 api 생성

src/main/java/com/teamddd/duckmap/controller/AuthController.java, src/main/java/com/teamddd/duckmap/controller/UserController.java, src/main/java/com/teamddd/duckmap/dto/user/CreateUserReq.java, src/main/java/com/teamddd/duckmap/dto/user/CreateUserRes.java, src/main/java/com/teamddd/duckmap/dto/user/UpdatePasswordReq.java, src/main/java/com/teamddd/duckmap/dto/user/UpdateUserReq.java, src/main/java/com/teamddd/duckmap/dto/user/UserRes.java, src/main/java/com/teamddd/duckmap/dto/user/auth/LoginUserReq.java, src/main/java/com/teamddd/duckmap/dto/user/auth/LoginUserRes.java
> User CRUD api 생성
- UserController
- POST /users 회원가입
- GET /users/me 로그인한 회원 정보 조회
- PUT  /users/me 로그인한 회원의 닉네임, 프로필 사진 변경 요청
- PATCH /users/me/password 로그인 한 회원의 비밀번호 변경
- GET /users/me 회원 탈퇴
- dto/user/auth로 auth 관련 dto 이동
- dto/user로 user 관련 dto 이동
- 닉네임 중복 확인 기능 삭제 고려
- 비밀번호 재설정 기능 개발 보류
=> User CRUD api 생성

src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkFolderEventDto.java, src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepository.java, src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryCustom.java, src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryImpl.java, src/test/java/com/teamddd/duckmap/BookmarkFolderRepositoryTest.java
> 북마크 폴더 내부 이벤트 조회 오류 수정 및 기능 개선
- BookmarkFolderRepositoryImpl 쿼리dsl 수정 
- Where 절 추가
- left join 대신 join 사용
- BookmarkFolderRepositoryTest 내용 추가
- BookmarkFolderRepositoryTest @Test import 변경
- BookmarkFolderRepositoryTest 
- createEventBookmark, createEventBookmarkFolder 연관관계의 주인 고려하여 수정
- 북마크 생성시 필수로 북마크 폴더가 필요함
- 컬렉션 조회 최적화 적용
- 폴더 여러개 생성 후 테스트 적용
- 이벤트 생성시 storeName만 지정(이벤트를 구분할 수 있는 정보 최소화하여 적용)
=> Fix: #89 - 북마크 폴더 내부 이벤트 조회 오류 수정 

src/main/java/com/teamddd/duckmap/repository/EventRepositoryCustom.java, src/main/java/com/teamddd/duckmap/repository/EventRepositoryImpl.java, src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java
> 단건 조회 객체를 Optional로 반환하여 null 반환을 방지한다
- EventRepositoryCustom
=> Refactor: Optional 반환으로 수정

src/main/java/com/teamddd/duckmap/advice/AuthAdvice.java, src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java, src/main/java/com/teamddd/duckmap/dto/ErrorResult.java, src/main/java/com/teamddd/duckmap/exception/InvalidTokenException.java, src/main/java/com/teamddd/duckmap/util/MemberUtils.java
> 인증된 Member 조회하는 util 생성
- MemberUtils 구현
- 인증된 Member가 없으면 InvalidTokenException 발생
- AuthAdvice에서 인증관련 ErrorResult response 반환
- ErrorResult로 exception response 생성
- enum ExceptionCodeMessage으로 error code, message 관리
=> Feat: #167 - MemberUtils 구현

src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java, src/main/java/com/teamddd/duckmap/config/security/JwtProvider.java, src/main/java/com/teamddd/duckmap/config/security/SecurityUserDetailsService.java, src/main/java/com/teamddd/duckmap/exception/InvalidMemberException.java, src/main/java/com/teamddd/duckmap/service/MemberService.java
> 사용자 인증 불가 Exception 구현(InvalidMemberException)
- INVALID_MEMBER_EXCEPTION("A002", "유효하지 않은 이메일 혹은 비밀번호입니다") 생성
- JwtProvider에서 토큰에서 인증 정보 조회시 userDetailsService 대신 custom한 securityUserDetailsService 사용
- SecurityUserDetailsService: Optional 사용 코드 개선
=> Feat: #182 - 사용자 인증 불가 Exception 구현(InvalidMemberException)

src/main/java/com/teamddd/duckmap/config/security/SecurityRule.java, src/main/java/com/teamddd/duckmap/controller/ArtistTypeController.java, src/test/java/com/teamddd/duckmap/controller/ArtistTypeControllerTest.java
> artist type 생성 요청시 관리자 권한 확인 로직 추가
- ArtistTypeController 아티스트 구분 등록 api에 @PreAuthorize 적용
=> Feat: #173 - 관리자 권한만 artist type 저장 가능

src/main/java/com/teamddd/duckmap/controller/MemberController.java, src/main/java/com/teamddd/duckmap/dto/user/DeleteMemberReq.java, src/main/java/com/teamddd/duckmap/service/MemberService.java
> 회원 탈퇴시 비밀번호 확인 로직 구현
- DeleteMemberReq 생성
- 회원 탈퇴 API에 비밀번호 확인하는 validatePassword()를 호출하여 비밀번호 확인을 먼저 한다.
=> Feat: #233 - 회원 탈퇴시 비밀번호 확인 로직 구현

src/main/java/com/teamddd/duckmap/config/security/JwtProvider.java, src/main/java/com/teamddd/duckmap/controller/AuthController.java, src/main/java/com/teamddd/duckmap/service/AuthService.java
> access 토큰과 refresh 토큰의 검증 및 재발급 기능 구현 완료
- 로그인시 client에 access token만 반환한다.
- 보안을 위해 refresh token은 redis에만 저장한다.
- /auth/validate 는 access token이 유효한지 확인한다. (유효할시 200, 유효하지 않을시 401)
- /auth/reissue 는 access token이 유효할때만 access token과 refresh token을 재발급한다.
- 이때 refresh token은 redis에서 찾아온다.
=> 토큰 검증 및 재발급 구현 완료

src/main/java/com/teamddd/duckmap/config/security/JwtProvider.java, src/main/java/com/teamddd/duckmap/controller/AuthController.java, src/main/java/com/teamddd/duckmap/service/AuthService.java
>Front 단에서 Refresh 토큰 사용 편의를 위한 코드 리팩토링
- 로그인시 RT를 쿠키에 넣어 반환 하도록 수정
- 재발급시 RT만 받아서 AT, RT를 재발급 하도록 수정
- 쿠키 유효시간 9일에서 7일로 변경
- AuthService
- JwtProvider
=> #254 Refresh 토큰 관련 리팩토링

build.gradle, src/main/java/com/teamddd/duckmap/controller/AuthController.java, src/main/java/com/teamddd/duckmap/dto/user/auth/VerificationReq.java, src/main/java/com/teamddd/duckmap/service/MemberService.java, src/main/java/com/teamddd/duckmap/service/SendMailService.java
> 인증번호 생성 및 이메일 전송 구현
- build.gradle에 spring-boot-starter-mail 추가
- SendMailService
- mailSend 구현
- sendVerification 구현
- makeRandomNumber 구현
- VerificationReq 생성
- AuthController의 sendVerification() 구현
- application.yml에 SMTP 설정 추가 필요함 (디스코드로 전달 예정)
=> Feat: #259 - 인증번호 생성 및 이메일 전송 구현

src/main/java/com/teamddd/duckmap/advice/AuthAdvice.java, src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java, src/main/java/com/teamddd/duckmap/controller/MemberController.java, src/main/java/com/teamddd/duckmap/dto/user/ResetPasswordReq.java, src/main/java/com/teamddd/duckmap/exception/InvalidUuidException.java, src/main/java/com/teamddd/duckmap/service/MemberService.java
> 비밀번호 재설정 API 구현
- resetPassword 서비스 구현
- redis 에서 uuid가 유효한지 확인한다.
- redis에서 uuid로 email을 찾아온다.
- 비밀번호 재설정
- 비밀번호 업데이트 후 redis에서 uuid를 지운다.
- InvalidUuidException 생성
=> 비밀번호 재설정 API 구현

src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java, src/main/java/com/teamddd/duckmap/controller/EventController.java, src/main/java/com/teamddd/duckmap/exception/NonExistentEventCategoryException.java, src/main/java/com/teamddd/duckmap/repository/ArtistRepository.java, src/main/java/com/teamddd/duckmap/repository/EventCategoryRepository.java, src/main/java/com/teamddd/duckmap/service/ArtistService.java, src/main/java/com/teamddd/duckmap/service/EventCategoryService.java, src/main/java/com/teamddd/duckmap/service/EventService.java, src/test/java/com/teamddd/duckmap/repository/ArtistRepositoryTest.java, src/test/java/com/teamddd/duckmap/repository/EventCategoryRepositoryTest.java, src/test/java/com/teamddd/duckmap/service/ArtistServiceTest.java, src/test/java/com/teamddd/duckmap/service/EventCategoryServiceTest.java, src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> event 저장 기능 구현 및 api 적용
- EventService
- createEvent()
- 아티스트 pk 확인을 위해 ArtistService getArtistsByIds(), ArtistRepository findByIdIn() 구현
- 이벤트 카테고리 pk 확인을 위해 EventCategoryService getEventCategoriesByIds(), EventCategoryRepository findByIdIn() 구현
- POST /events
- 변경사항이 많은데 핵심은 EventService createEvent() 이고 나머지는 파생된 기능이에요
=> event 저장 기능 구현 및 api 적용

src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java, src/main/java/com/teamddd/duckmap/controller/EventController.java, src/main/java/com/teamddd/duckmap/dto/event/event/EventRes.java, src/main/java/com/teamddd/duckmap/entity/Event.java, src/main/java/com/teamddd/duckmap/exception/NonExistentEventException.java, src/main/java/com/teamddd/duckmap/repository/ReviewRepository.java, src/main/java/com/teamddd/duckmap/service/EventService.java, src/test/java/com/teamddd/duckmap/repository/ReviewRepositoryTest.java, src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> event 상세 정보 조회 기능 구현
- EventRes fromDate, toDate LocalDate로 변경
- EventRes review 목록 제거
- ReviewRepository Event의 평점 계산 기능 구현
- Event 진행중 여부 확인 기능 구현
- EventService getEventRes()
추후 리팩토링 예정
- EventArtist을 ArtistRes변환 과정에서 query 3번
- from event_artist where event.id = ?
- from artist where id in (?,?)
- from artist_type where id = ?
- EventInfoCategory을 EventCategoryRes변환 과정에서 query 2번
- from event_info_category where event.id = ?
- from event_category where id in (?, ?)
- EventRes boolean like, bookmark -> pk 반환
=> Feat: #279 - event 상세 정보 조회 기능 구현

src/main/java/com/teamddd/duckmap/advice/ServiceAdvice.java, src/main/java/com/teamddd/duckmap/common/ExceptionCodeMessage.java, src/main/java/com/teamddd/duckmap/controller/LikeController.java, src/main/java/com/teamddd/duckmap/exception/NonExistentEventLikeException.java, src/main/java/com/teamddd/duckmap/exception/NonExistentMemberException.java, src/main/java/com/teamddd/duckmap/repository/EventLikeRepository.java, src/main/java/com/teamddd/duckmap/service/EventLikeService.java, src/test/java/com/teamddd/duckmap/repository/EventLikeRepositoryTest.java, src/test/java/com/teamddd/duckmap/service/EventLikeServiceTest.java
> 이벤트 좋아요, 좋아요 취소 기능 구현
- LikeController
- EventLikeService
- EventLikeServiceTest
- EventLikeRepository 쿼리 추가
- EventLikeRepositoryTest 추가
- 이벤트 좋아요 id(pk)로 EventLike를 찾음
- EventLike가 없을시 NonExistentEventLikeException
- 이벤트 좋아요 취소시 로그인한 member와 좋아요한 member가 일치하는지 확인
- 일치하지 않을시 AuthenticationRequiredException 
- 사용하지 않는 EventLikeRepository, EventLikeRepositoryTest의 코드 삭제
=> 이벤트 좋아요, 좋아요 취소 기능 구현

src/main/java/com/teamddd/duckmap/advice/ArtistAdvice.java, src/main/java/com/teamddd/duckmap/advice/EventAdvice.java
> 누락된 @ExceptionHandler 생성하여 에러 발생 시 해당 에러코드, 메시지 response 생성 반환
- ApiControllerAdvice
- NotContentTypeImageException
- ArtistAdvice
- NonExistentArtistTypeException
- NonExistentArtistTypeException
- EventAdvice
- NonExistentEventCategoryException
- NonExistentEventException
=> Feat: #341 - 누락된 @ExceptionHandler 생성

src/main/java/com/teamddd/duckmap/controller/ReviewController.java, src/main/java/com/teamddd/duckmap/dto/review/ReviewSearchParam.java, src/main/java/com/teamddd/duckmap/dto/review/ReviewSearchServiceReq.java, src/main/java/com/teamddd/duckmap/dto/review/ReviewsRes.java, src/main/java/com/teamddd/duckmap/repository/ReviewRepositoryImpl.java, src/main/java/com/teamddd/duckmap/service/ReviewService.java, src/test/java/com/teamddd/duckmap/service/ReviewServiceTest.java
> artist, 날짜 기준 리뷰 목록 조회, 리뷰 이미지 목록 조회 구현
- ReviewController
- getReviews() 구현: artist, 날짜 기준 리뷰 목록 조회
- getReviewImages() 구현
- ReviewSearchParam의 진행중여부 검색 파라미터 이름 변경 및 타입 변경
- ReviewService
- getReviewsResList 구현
- getReviewsResPage 구현
- getReviewsResList Test 작성
- getReviewsResPage Test 작성
- fetch join 오류로 인한 ReviewRepositoryImpl 수정 
- #301 베이스의 브랜치에서 작업중이었어서 #301의 수정사항을 #353과 커밋을 같이 하게 되었습니다.
=> Feat: #301 #353 - artist, 날짜 기준 리뷰 목록 조회, 리뷰 이미지 목록 조회 구현

src/main/java/com/teamddd/duckmap/controller/BookmarkFolderController.java, src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkEventDto.java, src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkedEventRes.java, src/main/java/com/teamddd/duckmap/dto/event/bookmark/BookmarkedEventsServiceReq.java, src/main/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryImpl.java, src/main/java/com/teamddd/duckmap/service/BookmarkFolderService.java, src/test/java/com/teamddd/duckmap/repository/BookmarkFolderRepositoryTest.java, src/test/java/com/teamddd/duckmap/service/BookmarkFolderServiceTest.java
> 북마크 폴더 내부의 이벤트 목록 조회 구현
- BookmarkedEventsServiceReq 생성
- BookmarkedEventRes에 eventId 추가, of() 구현
- BookmarkEventDto에서 필요한 컬럼만 조회하도록 변경
- BookmarkFolderRespositoryImpl
- findBookmarkedEvents() 에서 필요한 컬럼만 조회
- image는 thumbnail이 true인 것만 가져옴
- BookmarkFolderService, BookmarkFolderController
- getBookmarkedEventResList(), getAllBookmarks() 구현
-  BookmarkFolderServiceTest, BookmarkFolderRepositoryTest
- 쿼리 변경에 따른 테스트 코드 변경 
- findBookmarkedEvents(), getBookmarkedEvents() 테스트 작성
=> Feat: #363 - 북마크 폴더 내부의 이벤트 목록 조회 구현

src/main/java/com/teamddd/duckmap/controller/ReviewController.java, src/main/java/com/teamddd/duckmap/dto/review/EventReviewServiceReq.java, src/main/java/com/teamddd/duckmap/dto/review/EventReviewsRes.java, src/main/java/com/teamddd/duckmap/repository/ReviewRepository.java, src/main/java/com/teamddd/duckmap/service/ReviewService.java, src/test/java/com/teamddd/duckmap/repository/ReviewRepositoryTest.java, src/test/java/com/teamddd/duckmap/service/ReviewServiceTest.java
> 이벤트 pk로 리뷰 목록 조회
- EventReviewServiceReq, EventReviewsRes 생성
- ReviewRepository : findByEventId() 추가
- ReviewService, ReviewController
- 이벤트의 리뷰 목록 조회하는 getEventReviews() 구현 
- ReviewRepositoryTest, ReviewServiceTest
- findByEventId(), getEventReviewsResList() Test 코드 작성
- 불필요한 em.flush(), em.clear() 제거
- 각 테스트에 reviewImage 확인 추가
=> Feat: #372 - 이벤트 pk로 리뷰 목록 조회

src/main/java/com/teamddd/duckmap/controller/EventController.java, src/main/java/com/teamddd/duckmap/entity/Event.java, src/main/java/com/teamddd/duckmap/repository/EventBookmarkRepository.java, src/main/java/com/teamddd/duckmap/service/EventService.java, src/test/java/com/teamddd/duckmap/repository/EventBookmarkRepositoryTest.java, src/test/java/com/teamddd/duckmap/repository/EventLikeRepositoryTest.java, src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> event 삭제 기능 구현
- Event
- Event cascade.REMOVE, orphanRemoval 는 delete query가 n번 발생해서 bulk로 대체
- EventService deleteEvent()
- EventLikeRepository deleteByEventId()
- EventBookmarkRepository deleteByEventId()
- EventController deleteEvent()
=> Feat: #430 - event 삭제 기능 구현

src/main/java/com/teamddd/duckmap/controller/EventController.java, src/main/java/com/teamddd/duckmap/dto/event/event/EventLikeReviewCountDto.java, src/main/java/com/teamddd/duckmap/dto/event/event/EventPageReq.java, src/main/java/com/teamddd/duckmap/dto/event/event/EventsMapRes.java, src/main/java/com/teamddd/duckmap/entity/EventArtist.java, src/main/java/com/teamddd/duckmap/repository/EventRepositoryCustom.java, src/main/java/com/teamddd/duckmap/repository/EventRepositoryImpl.java, src/main/java/com/teamddd/duckmap/service/EventService.java, src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java, src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> 지도 표기용 Event 목록 조회 기능 구현
- EventArtist Artist 외래키 제약조건 제거
- EventController getEventsForMap()
- EventPageReq
- EventsMapRes
- EventService getEventsForMap()
- EventRepository findForMap()
- EventLikeReviewCountDto
=> Feat: #422 - 지도 표기용 Event 목록 조회 기능 구현

src/main/java/com/teamddd/duckmap/controller/EventController.java, src/main/java/com/teamddd/duckmap/dto/event/event/HashtagRes.java, src/main/java/com/teamddd/duckmap/repository/EventRepository.java, src/main/java/com/teamddd/duckmap/service/EventService.java, src/test/java/com/teamddd/duckmap/repository/EventRepositoryTest.java, src/test/java/com/teamddd/duckmap/service/EventServiceTest.java
> 날짜 기준 event의 hashtag 목록 조회 기능 구현
- EventController getTodayHashtags()
- HashtagRes of()
- EventService getHashtagResListByDate()
- EventRepository findByArtistAndDate()
=> Feat: #436 - 날짜 기준 event의 hashtag 목록 조회 기능 구현

.github/workflows/close-issue.yml, src/main/java/com/teamddd/duckmap/controller/EventController.java, src/main/java/com/teamddd/duckmap/dto/event/event/EventSearchServiceReq.java, src/main/java/com/teamddd/duckmap/entity/LastSearchArtist.java, src/main/java/com/teamddd/duckmap/repository/LastSearchArtistRepository.java, src/main/java/com/teamddd/duckmap/service/EventService.java, src/main/java/com/teamddd/duckmap/service/LastSearchArtistService.java, src/test/java/com/teamddd/duckmap/repository/LastSearchArtistRepositoryTest.java, src/test/java/com/teamddd/duckmap/service/EventServiceTest.java, src/test/java/com/teamddd/duckmap/service/LastSearchArtistServiceTest.java
> event 목록 조회 시 LastSearchArtist 값 변경 기능 구현
- LastSearchArtist
- Member unique 조건 추가
- changeSearchArtist() 구현
- EventController getEvents()
- EventSearchServiceReq Long memberId -> Optional<Member> member
- EventService getEventsResList()
- EventSearchServiceReq에 artistId와 member가 있으면 LastSearchArtist 저장 기능 호출
- LastSearchArtistService saveLastSearchArtist()
- LastSearchArtistRepository findByMember()
변경사항이 너무 많네요.. 커밋을 나눴어야 했는데 죄송합니다
=> Feat: #439 - event 목록 조회 시 LastSearchArtist 값 변경 기능 구현

src/main/java/com/teamddd/duckmap/repository/ArtistRepositoryImpl.java, src/test/java/com/teamddd/duckmap/repository/ArtistRepositoryTest.java
> 아티스트 목록 조회시 아티스트 타입 id, 아티스트 이름 오름차순으로 sort 적용
- ArtistRepository findByTypeAndName()
=> Feat: #444 - 아티스트 목록 조회시 아티스트 타입 id로 sort 적용

src/main/java/com/teamddd/duckmap/dto/event/event/EventsRes.java
> Artist가 없는 EventsRes 변환 시 에러 발생
- EventsRes of()
버그라서 메인에 pr 했습니다
=> Fix: #465 - Artist가 없는 EventsRes 변환 시 에러 발생

src/main/java/com/teamddd/duckmap/repository/ReviewRepository.java, src/main/java/com/teamddd/duckmap/service/EventService.java, src/test/java/com/teamddd/duckmap/repository/ReviewRepositoryTest.java
> Event 제거 시 Review fk null로 변경
- EventService deleteEvent()
- ReviewRepository updateEventToNull()
=> Feat: #470 - Event 제거 시 Review fk null로 변경

src/main/java/com/teamddd/duckmap/controller/AuthController.java
> 로그인시 Set-Cookie로 브라우저에 쿠키가 자동 저장 되도록 수정한다.
- httpOnly를 true로 변경
- sameSite를 None, secure를 true로 설정하여 Cross Domain에서 제약없이 저장하도록 함
=> ResponseCookie 관련 설정 변경

src/main/java/com/teamddd/duckmap/controller/ReviewController.java
> getEventReviews()에 mapping된 URL이 다른 URL과 동일하지 않도록 수정
-  Ambiguous handler methods mapped for HTTP path 오류 발생하여 해당 URL을 수정했습니다. 
- @GetMapping("/{id}")와 @GetMapping("/{eventId}")는 같은 GET 요청, Long 타입이기 때문에 동일한 URL로 받아들여진다고 합니다. 
- 따라서 이벤트의 리뷰 목록 조회는 구분해주기 위하여 @GetMapping("/event/{eventId}")로 변경했습니다.
=> getEventReviews()에 mapping된 URL이 다른 URL과 동일하지 않도록 수정

src/main/java/com/teamddd/duckmap/dto/review/ReviewRes.java, src/main/java/com/teamddd/duckmap/dto/review/ReviewsRes.java
> https://github.com/duck-map-project/duck-map-be/issues/517
- 리뷰 전체 목록을 조회할 때 별점, 아티스트list, 카테고리list를 반환
- 리뷰 상세정보를 조회할 때 이벤트 id, 상호명, 해시태그를 반환
=> 리뷰 전체 목록 조회 api,리뷰 상세정보 조회 api 수정

src/main/java/com/teamddd/duckmap/controller/AuthController.java
> 토큰 재발급 API에서 sameSite None 설정
- HttpCookie를 ResponseCookie로 변경
- 재발급 API에서 누락된 sameSite None 설정 추가
=> Refactor: #545 - 토큰 재발급 API에서 sameSite None 설정
